/** File extension -> syntax language id shared by CodeMirror and Shiki. */
const EXT_LANG_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  jsx: 'jsx',
  mts: 'typescript',
  cts: 'typescript',
  mjs: 'javascript',
  cjs: 'javascript',
  rs: 'rust',
  go: 'go',
  c: 'c',
  h: 'c',
  cpp: 'cpp',
  cxx: 'cpp',
  cc: 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  hh: 'cpp',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  scala: 'scala',
  dart: 'dart',
  cs: 'csharp',
  py: 'python',
  pyi: 'python',
  rb: 'ruby',
  swift: 'swift',
  lua: 'lua',
  pl: 'perl',
  pm: 'perl',
  r: 'r',
  jl: 'julia',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hs: 'haskell',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  elm: 'elm',
  ml: 'ocaml',
  mli: 'ocaml',
  fs: 'fsharp',
  fsx: 'fsharp',
  groovy: 'groovy',
  gradle: 'groovy',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'bash',
  ps1: 'powershell',
  psm1: 'powershell',
  psd1: 'powershell',
  tcl: 'tcl',
  json: 'json',
  jsonc: 'jsonc',
  json5: 'json',
  toml: 'toml',
  yaml: 'yaml',
  yml: 'yaml',
  ini: 'properties',
  conf: 'properties',
  properties: 'properties',
  env: 'properties',
  html: 'html',
  htm: 'html',
  xhtml: 'html',
  xml: 'xml',
  svg: 'xml',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  styl: 'stylus',
  stylus: 'stylus',
  vue: 'vue',
  svelte: 'svelte',
  php: 'php',
  phtml: 'php',
  md: 'markdown',
  mdx: 'mdx',
  markdown: 'markdown',
  sql: 'sql',
  graphql: 'graphql',
  gql: 'graphql',
  dockerfile: 'dockerfile',
  diff: 'diff',
  patch: 'diff',
  lock: 'json',
  nix: 'nix',
  tf: 'terraform',
  hcl: 'terraform',
  proto: 'protobuf',
  cmake: 'cmake',
}

const BASENAME_LANG_MAP: Record<string, string> = {
  dockerfile: 'dockerfile',
  containerfile: 'dockerfile',
  makefile: 'makefile',
  gnumakefile: 'makefile',
  rakefile: 'ruby',
  gemfile: 'ruby',
  procfile: 'properties',
  '.env': 'properties',
  '.gitignore': 'properties',
  '.gitattributes': 'properties',
  '.dockerignore': 'properties',
  '.npmrc': 'properties',
  '.editorconfig': 'properties',
  'cmakelists.txt': 'cmake',
}

export function getLangFromPath(filePath: string): string | null {
  const slash = Math.max(filePath.lastIndexOf('/'), filePath.lastIndexOf('\\'))
  const base = filePath.slice(slash + 1).toLowerCase()
  if (!base) return null

  const byBasename = BASENAME_LANG_MAP[base]
  if (byBasename) return byBasename

  const dot = base.lastIndexOf('.')
  if (dot <= 0) return null
  const ext = base.slice(dot + 1)
  return EXT_LANG_MAP[ext] ?? null
}
