pub mod agent_core;
pub mod autonomous_orchestrator;
pub mod autonomous_skill_runtime;
pub mod autonomous_tool_runtime;
pub mod autonomous_web_runtime;
pub mod diagnostics;
pub mod platform_adapter;
pub mod pricing;
pub(crate) mod process_tree;
pub mod protocol;
pub mod provider;
pub(crate) mod redaction;
pub mod supervisor;
pub mod usage_events;

pub use agent_core::{
    append_user_message, cancel_owned_agent_run, cancelled_error, continue_owned_agent_run,
    create_owned_agent_run, create_provider_adapter, drive_owned_agent_continuation,
    drive_owned_agent_run, prepare_owned_agent_continuation,
    prepare_owned_agent_continuation_for_drive, run_agent_definition_quality_eval_suite,
    run_agent_harness_eval_suite, run_owned_agent_task, run_xero_quality_eval_suites,
    subscribe_agent_events, AgentAutoCompactPreference, AgentDefinitionEvalFixtureKind,
    AgentDefinitionQualityCaseResult, AgentDefinitionQualityCoverage,
    AgentDefinitionQualityEvalReport, AgentDefinitionQualityMetrics, AgentDefinitionQualitySurface,
    AgentDefinitionQualityThresholds, AgentEventSubscription, AgentHarnessEvalCaseResult,
    AgentHarnessEvalCoverage, AgentHarnessEvalMetrics, AgentHarnessEvalReport,
    AgentHarnessEvalThresholds, AgentProviderConfig, AgentRunCancellationToken, AgentRunSupervisor,
    AgentSafetyDecision, AgentToolCall, AgentToolDescriptor, AgentToolResult,
    AnthropicProviderConfig, BedrockProviderConfig, ContinueOwnedAgentRunRequest,
    FakeProviderAdapter, HarnessEvalFixtureKind, MessageAttachment, MessageAttachmentKind,
    OpenAiCodexResponsesProviderConfig, OpenAiCompatibleProviderConfig,
    OpenAiResponsesProviderConfig, OwnedAgentRunRequest,
    PreparedOwnedAgentContinuation, ProviderAdapter, ProviderMessage, ProviderStreamEvent,
    ProviderTurnOutcome, ProviderTurnRequest, ProviderUsage, ToolRegistry, ToolRegistryOptions,
    VertexProviderConfig, XeroQualityEvalReport, AGENT_RUN_CANCELLED_CODE, FAKE_PROVIDER_ID,
    OWNED_AGENT_RUNTIME_KIND, OWNED_AGENT_SUPERVISOR_KIND,
};
pub use autonomous_skill_runtime::{
    decide_skill_tool_access, discover_bundled_skill_directory, discover_local_skill_directory,
    discover_plugin_roots, discover_plugin_skill_contribution, discover_project_skill_directory,
    load_discovered_skill_context, load_skill_source_settings_from_path,
    merge_skill_source_records, model_may_discover_skill_source, normalize_plugin_contribution_id,
    normalize_plugin_id, parse_plugin_manifest, persist_skill_source_settings,
    plugin_command_stable_id, plugin_trust_declaration_to_skill_trust,
    skill_tool_diagnostic_from_command_error, validate_skill_source_state_transition,
    validate_skill_tool_context_payload, validate_skill_tool_input,
    validate_skill_tool_lifecycle_event, AutonomousSkillCacheError,
    AutonomousSkillCacheInstallFile, AutonomousSkillCacheManifest,
    AutonomousSkillCacheManifestFile, AutonomousSkillCacheStatus, AutonomousSkillCacheStore,
    AutonomousSkillDiscoverOutput, AutonomousSkillDiscoverRequest,
    AutonomousSkillDiscoveryCandidate, AutonomousSkillInstallOutput, AutonomousSkillInstallRequest,
    AutonomousSkillInvocationAsset, AutonomousSkillInvokeOutput, AutonomousSkillInvokeRequest,
    AutonomousSkillRegistryFailure, AutonomousSkillRegistryOperation, AutonomousSkillRegistrySink,
    AutonomousSkillRegistrySuccess, AutonomousSkillResolveOutput, AutonomousSkillResolveRequest,
    AutonomousSkillRuntime, AutonomousSkillRuntimeConfig, AutonomousSkillRuntimeLimits,
    AutonomousSkillSource, AutonomousSkillSourceEntryKind, AutonomousSkillSourceError,
    AutonomousSkillSourceFileRequest, AutonomousSkillSourceFileResponse,
    AutonomousSkillSourceMetadata, AutonomousSkillSourceTreeEntry,
    AutonomousSkillSourceTreeRequest, AutonomousSkillSourceTreeResponse,
    FilesystemAutonomousSkillCacheStore, GithubAutonomousSkillSource, SkillGithubSourceSetting,
    SkillLocalRootSetting, SkillPluginRootSetting, SkillProjectSourceSetting, SkillSourceSettings,
    XeroDiscoveredPlugin, XeroDiscoveredSkill, XeroPluginCommandApprovalPolicy,
    XeroPluginCommandAvailability, XeroPluginCommandContribution, XeroPluginCommandRiskLevel,
    XeroPluginCommandStatePolicy, XeroPluginDiscovery, XeroPluginDiscoveryDiagnostic,
    XeroPluginEntryKind, XeroPluginEntryLocation, XeroPluginManifest, XeroPluginRoot,
    XeroPluginSkillContribution, XeroPluginTrustDeclaration, XeroSkillDirectoryDiscovery,
    XeroSkillDiscoveryDiagnostic, XeroSkillSourceKind, XeroSkillSourceLocator,
    XeroSkillSourceRecord, XeroSkillSourceScope, XeroSkillSourceState, XeroSkillToolAccessDecision,
    XeroSkillToolAccessStatus, XeroSkillToolContextAsset, XeroSkillToolContextDocument,
    XeroSkillToolContextPayload, XeroSkillToolDiagnostic, XeroSkillToolDynamicAssetInput,
    XeroSkillToolInput, XeroSkillToolLifecycleEvent, XeroSkillToolLifecycleResult,
    XeroSkillToolOperation, XeroSkillTrustState, AUTONOMOUS_SKILL_SOURCE_REF,
    AUTONOMOUS_SKILL_SOURCE_REPO, AUTONOMOUS_SKILL_SOURCE_ROOT, PROJECT_SKILL_DIRECTORY,
    XERO_PLUGIN_MANIFEST_FILE, XERO_PLUGIN_MANIFEST_SCHEMA_VERSION,
    XERO_PLUGIN_NESTED_MANIFEST_FILE, XERO_SKILL_SOURCE_CONTRACT_VERSION,
    XERO_SKILL_TOOL_CONTRACT_VERSION, XERO_SKILL_TOOL_DEFAULT_LIMIT,
    XERO_SKILL_TOOL_MAX_CONTEXT_ASSETS, XERO_SKILL_TOOL_MAX_CONTEXT_ASSET_BYTES,
    XERO_SKILL_TOOL_MAX_CONTEXT_MARKDOWN_BYTES, XERO_SKILL_TOOL_MAX_LIMIT,
    XERO_SKILL_TOOL_MAX_QUERY_CHARS,
};
pub use autonomous_tool_runtime::{
    resolve_imported_repo_root, resolve_imported_repo_root_from_registry,
    AutonomousAgentDefinitionAction, AutonomousAgentDefinitionOutput,
    AutonomousAgentDefinitionRequest, AutonomousAgentDefinitionSummary,
    AutonomousAgentDefinitionValidationDiagnostic, AutonomousAgentDefinitionValidationReport,
    AutonomousAgentDefinitionValidationStatus, AutonomousBundledSkillRoot,
    AutonomousCodeDiagnostic, AutonomousCodeIntelAction, AutonomousCodeIntelOutput,
    AutonomousCodeIntelRequest, AutonomousCodeSymbol, AutonomousCommandOutput,
    AutonomousCommandPolicyOutcome, AutonomousCommandPolicyTrace, AutonomousCommandRequest,
    AutonomousCommandSessionChunk, AutonomousCommandSessionOperation,
    AutonomousCommandSessionOutput, AutonomousCommandSessionReadRequest,
    AutonomousCommandSessionStartRequest, AutonomousCommandSessionStopRequest,
    AutonomousCommandSessionStream, AutonomousDeleteOutput, AutonomousDeleteRequest,
    AutonomousDynamicToolDescriptor, AutonomousDynamicToolRoute, AutonomousEditOutput,
    AutonomousEditRequest, AutonomousEnvironmentContextAction, AutonomousEnvironmentContextOutput,
    AutonomousEnvironmentContextRequest, AutonomousFindOutput, AutonomousFindRequest,
    AutonomousGitDiffOutput, AutonomousGitDiffRequest, AutonomousGitStatusOutput,
    AutonomousGitStatusRequest, AutonomousHashOutput, AutonomousHashRequest, AutonomousLineEnding,
    AutonomousListEntry, AutonomousListOutput, AutonomousListRequest, AutonomousLocalSkillRoot,
    AutonomousLspAction, AutonomousLspInstallCommand, AutonomousLspInstallSuggestion,
    AutonomousLspOutput, AutonomousLspRequest, AutonomousLspServerStatus, AutonomousMacosApp,
    AutonomousMacosAutomationAction, AutonomousMacosAutomationOutput,
    AutonomousMacosAutomationPolicyTrace, AutonomousMacosAutomationRequest,
    AutonomousMacosPermission, AutonomousMacosPermissionStatus, AutonomousMacosScreenshot,
    AutonomousMacosScreenshotTarget, AutonomousMacosWindow, AutonomousMacosWindowBounds,
    AutonomousMcpAction, AutonomousMcpOutput, AutonomousMcpRequest, AutonomousMcpServerSummary,
    AutonomousMkdirOutput, AutonomousMkdirRequest, AutonomousNotebookEditOutput,
    AutonomousNotebookEditRequest, AutonomousPatchFailure, AutonomousPatchFileOutput,
    AutonomousPatchOperation, AutonomousPatchOutput, AutonomousPatchRequest, AutonomousPluginRoot,
    AutonomousPowerShellRequest, AutonomousProcessActionRiskLevel,
    AutonomousProcessCommandMetadata, AutonomousProcessLifecycleContract,
    AutonomousProcessManagerAction, AutonomousProcessManagerContract,
    AutonomousProcessManagerOutput, AutonomousProcessManagerPolicyTrace,
    AutonomousProcessManagerRequest, AutonomousProcessMetadata, AutonomousProcessOutputChunk,
    AutonomousProcessOutputLimits, AutonomousProcessOutputStream, AutonomousProcessOwner,
    AutonomousProcessOwnershipScope, AutonomousProcessPersistenceContract,
    AutonomousProcessReadinessDetector, AutonomousProcessReadinessState, AutonomousProcessStatus,
    AutonomousProjectContextAction, AutonomousProjectContextMemory,
    AutonomousProjectContextMemoryKind, AutonomousProjectContextOutput,
    AutonomousProjectContextRecord, AutonomousProjectContextRecordImportance,
    AutonomousProjectContextRecordKind, AutonomousProjectContextRequest,
    AutonomousProjectContextResult, AutonomousReadContentKind, AutonomousReadLineHash,
    AutonomousReadMode, AutonomousReadOutput, AutonomousReadRequest, AutonomousRenameOutput,
    AutonomousRenameRequest, AutonomousSafetyApprovalGrant, AutonomousSafetyPolicyAction,
    AutonomousSafetyPolicyDecision, AutonomousSearchContextLine, AutonomousSearchMatch,
    AutonomousSearchOutput, AutonomousSearchRequest, AutonomousSkillToolCandidate,
    AutonomousSkillToolOutput, AutonomousSkillToolStatus, AutonomousSubagentAction,
    AutonomousSubagentExecutor, AutonomousSubagentOutput, AutonomousSubagentRequest,
    AutonomousSubagentRole, AutonomousSubagentTask, AutonomousSubagentWriteScope,
    AutonomousSystemDiagnosticsAction, AutonomousSystemDiagnosticsArtifact,
    AutonomousSystemDiagnosticsArtifactMode, AutonomousSystemDiagnosticsDiagnostic,
    AutonomousSystemDiagnosticsFdKind, AutonomousSystemDiagnosticsLogLevel,
    AutonomousSystemDiagnosticsOutput, AutonomousSystemDiagnosticsPolicyTrace,
    AutonomousSystemDiagnosticsPreset, AutonomousSystemDiagnosticsRequest,
    AutonomousSystemDiagnosticsRow, AutonomousSystemDiagnosticsTarget, AutonomousSystemPort,
    AutonomousTodoAction, AutonomousTodoItem, AutonomousTodoOutput, AutonomousTodoRequest,
    AutonomousTodoStatus, AutonomousToolAccessAction, AutonomousToolAccessGroup,
    AutonomousToolAccessOutput, AutonomousToolAccessRequest, AutonomousToolCommandResult,
    AutonomousToolOutput, AutonomousToolRequest, AutonomousToolResult, AutonomousToolRuntime,
    AutonomousToolRuntimeLimits, AutonomousToolSearchMatch, AutonomousToolSearchOutput,
    AutonomousToolSearchRequest, AutonomousWriteOutput, AutonomousWriteRequest,
    AUTONOMOUS_TOOL_AGENT_DEFINITION, AUTONOMOUS_TOOL_CODE_INTEL, AUTONOMOUS_TOOL_COMMAND,
    AUTONOMOUS_TOOL_COMMAND_SESSION_READ, AUTONOMOUS_TOOL_COMMAND_SESSION_START,
    AUTONOMOUS_TOOL_COMMAND_SESSION_STOP, AUTONOMOUS_TOOL_DELETE, AUTONOMOUS_TOOL_EDIT,
    AUTONOMOUS_TOOL_ENVIRONMENT_CONTEXT, AUTONOMOUS_TOOL_FIND, AUTONOMOUS_TOOL_GIT_DIFF,
    AUTONOMOUS_TOOL_GIT_STATUS, AUTONOMOUS_TOOL_HASH, AUTONOMOUS_TOOL_LIST, AUTONOMOUS_TOOL_LSP,
    AUTONOMOUS_TOOL_MACOS_AUTOMATION, AUTONOMOUS_TOOL_MCP, AUTONOMOUS_TOOL_MKDIR,
    AUTONOMOUS_TOOL_NOTEBOOK_EDIT, AUTONOMOUS_TOOL_PATCH, AUTONOMOUS_TOOL_POWERSHELL,
    AUTONOMOUS_TOOL_PROCESS_MANAGER, AUTONOMOUS_TOOL_PROJECT_CONTEXT, AUTONOMOUS_TOOL_READ,
    AUTONOMOUS_TOOL_RENAME, AUTONOMOUS_TOOL_SEARCH, AUTONOMOUS_TOOL_SKILL,
    AUTONOMOUS_TOOL_SUBAGENT, AUTONOMOUS_TOOL_SYSTEM_DIAGNOSTICS, AUTONOMOUS_TOOL_TODO,
    AUTONOMOUS_TOOL_TOOL_ACCESS, AUTONOMOUS_TOOL_TOOL_SEARCH, AUTONOMOUS_TOOL_WRITE,
};
pub use autonomous_web_runtime::{
    AutonomousWebConfig, AutonomousWebFetchContentKind, AutonomousWebFetchOutput,
    AutonomousWebFetchRequest, AutonomousWebRuntime, AutonomousWebRuntimeLimits,
    AutonomousWebSearchOutput, AutonomousWebSearchProviderConfig, AutonomousWebSearchRequest,
    AutonomousWebTransport, AutonomousWebTransportError, AutonomousWebTransportRequest,
    AutonomousWebTransportResponse, AUTONOMOUS_TOOL_WEB_FETCH, AUTONOMOUS_TOOL_WEB_SEARCH,
};
pub use diagnostics::{
    ambient_auth_failure_diagnostic, invalid_base_url_diagnostic,
    provider_model_catalog_diagnostic, provider_readiness_diagnostic,
    provider_validation_diagnostics, render_doctor_report, sanitize_diagnostic_text,
    stale_runtime_binding_diagnostic, summarize_diagnostic_checks, unsupported_provider_diagnostic,
    validate_diagnostic_check, validate_doctor_report, XeroDiagnosticCheck,
    XeroDiagnosticCheckInput, XeroDiagnosticEndpointMetadata, XeroDiagnosticRedactionClass,
    XeroDiagnosticSeverity, XeroDiagnosticStatus, XeroDiagnosticSubject, XeroDoctorReport,
    XeroDoctorReportInput, XeroDoctorReportMode, XeroDoctorReportOutputMode,
    XeroDoctorReportSummary, XeroDoctorVersionInfo, XERO_DIAGNOSTIC_CONTRACT_VERSION,
    XERO_DOCTOR_REPORT_CONTRACT_VERSION,
};
pub use platform_adapter::{
    bind_openai_callback_listener, default_openai_callback_policy, resolve_openai_callback_policy,
    resolve_runtime_shell_selection, resolve_runtime_shell_selection_for_platform,
    OpenAiCallbackBindResult, OpenAiCallbackPolicy, RuntimeAdapterDiagnostic, RuntimePlatform,
    RuntimeShellSelection, RuntimeShellSource,
};
pub use protocol::RuntimeSupervisorLaunchContext;
pub use provider::{
    anthropic_provider, azure_openai_provider, bedrock_provider, default_runtime_provider,
    gemini_ai_studio_provider, github_models_provider, logout_provider_runtime_session,
    normalize_openai_codex_model_id, ollama_provider, openai_api_provider, openai_codex_provider,
    openrouter_provider, refresh_provider_runtime_session, resolve_runtime_provider_identity,
    vertex_provider, ResolvedRuntimeProvider, RuntimeProvider, RuntimeProviderBindOutcome,
    RuntimeProviderReconcileOutcome, RuntimeProviderSessionBinding, ANTHROPIC_PROVIDER_ID,
    ANTHROPIC_RUNTIME_KIND, AZURE_OPENAI_PROVIDER_ID, BEDROCK_PROVIDER_ID,
    GEMINI_AI_STUDIO_PROVIDER_ID, GEMINI_RUNTIME_KIND, GITHUB_MODELS_PROVIDER_ID,
    OLLAMA_PROVIDER_ID, OPENAI_API_PROVIDER_ID, OPENAI_CODEX_DEFAULT_MODEL_ID,
    OPENAI_CODEX_PROVIDER_ID, OPENAI_CODEX_SUPPORTED_MODEL_IDS, OPENAI_COMPATIBLE_RUNTIME_KIND,
    OPENROUTER_PROVIDER_ID, VERTEX_PROVIDER_ID,
};
pub(crate) use provider::{bind_provider_runtime_session, reconcile_provider_runtime_session};
pub use supervisor::{
    launch_legacy_runtime_supervisor, probe_runtime_run, run_supervisor_sidecar_from_env,
    stop_runtime_run, submit_runtime_run_input, update_runtime_run_controls,
    RuntimeSupervisorController, RuntimeSupervisorLaunchEnv, RuntimeSupervisorLaunchRequest,
    RuntimeSupervisorProbeRequest, RuntimeSupervisorStopRequest,
    RuntimeSupervisorSubmitInputRequest, RuntimeSupervisorUpdateControlsRequest,
};
