/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsComputerIdSessionIdRouteImport } from './routes/sessions.$computerId.$sessionId'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsComputerIdSessionIdRoute =
  SessionsComputerIdSessionIdRouteImport.update({
    id: '/$computerId/$sessionId',
    path: '/$computerId/$sessionId',
    getParentRoute: () => SessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/sessions/$computerId/$sessionId': typeof SessionsComputerIdSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/sessions/$computerId/$sessionId': typeof SessionsComputerIdSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/sessions/$computerId/$sessionId': typeof SessionsComputerIdSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sessions' | '/sessions/$computerId/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sessions' | '/sessions/$computerId/$sessionId'
  id: '__root__' | '/' | '/sessions' | '/sessions/$computerId/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsRoute: typeof SessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$computerId/$sessionId': {
      id: '/sessions/$computerId/$sessionId'
      path: '/$computerId/$sessionId'
      fullPath: '/sessions/$computerId/$sessionId'
      preLoaderRoute: typeof SessionsComputerIdSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
  }
}

interface SessionsRouteChildren {
  SessionsComputerIdSessionIdRoute: typeof SessionsComputerIdSessionIdRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsComputerIdSessionIdRoute: SessionsComputerIdSessionIdRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsRoute: SessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
