import { COMPUTER_USE_SIDEBAR_COMPACT_WIDTH } from '@xero/ui/components/computer-use-sidebar'

export const AGENT_PANE_COMPACT_WIDTH_PX = 490
export const SIDEBAR_AGENT_PANE_COMPACT_WIDTH_PX = COMPUTER_USE_SIDEBAR_COMPACT_WIDTH
