use std::{
    collections::HashMap,
    fs,
    path::{Path, PathBuf},
};

use rand::RngCore;
use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Runtime, State};

use crate::{
    auth::now_timestamp,
    commands::{
        contracts::developer_tool_harness::{
            DeveloperToolCatalogEntryDto, DeveloperToolCatalogResponseDto,
            DeveloperToolDryRunRequestDto, DeveloperToolDryRunResponseDto,
            DeveloperToolHarnessCallDto, DeveloperToolHarnessCallResultDto,
            DeveloperToolHarnessProjectDto, DeveloperToolHarnessRunOptionsDto,
            DeveloperToolModelRunRequestDto, DeveloperToolModelRunResponseDto,
            DeveloperToolPackSummaryDto, DeveloperToolPolicyDecisionDto,
            DeveloperToolSequenceDeleteRequestDto, DeveloperToolSequenceListResponseDto,
            DeveloperToolSequenceRecordDto, DeveloperToolSequenceUpsertRequestDto,
            DeveloperToolSyntheticRunRequestDto, DeveloperToolSyntheticRunResponseDto,
        },
        start_agent_task, validate_non_empty, CommandError, CommandResult, RuntimeAgentIdDto,
        RuntimeRunApprovalModeDto, RuntimeRunControlInputDto, StartAgentTaskRequestDto,
    },
    db::{
        self,
        project_store::{self, AgentSessionCreateRecord},
        ProjectOrigin,
    },
    git::repository::CanonicalRepository,
    global_db::open_global_database,
    registry::{self, RegistryProjectRecord},
    runtime::agent_core::{
        builtin_tool_descriptors, dispatch_synthetic_tool_calls, dry_run_tool_call, AgentToolCall,
        SyntheticDispatchOptions, ToolRegistry, ToolRegistryOptions,
    },
    runtime::autonomous_tool_runtime::{
        allowed_runtime_agent_labels, deferred_tool_catalog, runtime_host_metadata,
        tool_available_on_current_host, tool_catalog_activation_groups, tool_effect_class,
        AutonomousToolRuntime,
    },
    state::DesktopState,
};
use xero_agent_core::{domain_tool_pack_ids_for_tool, domain_tool_pack_manifest};

use super::runtime_support::{generate_runtime_run_id, resolve_project_root};

pub const HARNESS_FIXTURE_PROJECT_ID: &str = "xero-developer-tool-harness-fixture";
const HARNESS_FIXTURE_REPOSITORY_ID: &str = "xero-developer-tool-harness-fixture-repo";
const HARNESS_FIXTURE_DISPLAY_NAME: &str = "Tool harness fixture";
const HARNESS_FIXTURE_DIRECTORY: &str = "developer-tool-harness/fixture";
const HARNESS_FIXTURE_README: &str = "# Tool harness fixture\n\nThis repository is auto-generated by Xero so the developer tool harness has a stable, isolated project to exercise tools against. Files here are deterministic and replaced whenever the harness needs them — do not store anything important in this folder.\n";
const HARNESS_FIXTURE_SAMPLE: &str = "alpha\nbeta\ngamma\n";

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DeveloperToolCatalogRequestDto {
    #[serde(default)]
    pub skill_tool_enabled: Option<bool>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DeveloperToolHarnessHostKind {
    Desktop,
    Terminal,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DeveloperToolCatalogServiceOptions {
    pub skill_tool_enabled: bool,
    pub host_kind: DeveloperToolHarnessHostKind,
}

impl Default for DeveloperToolCatalogServiceOptions {
    fn default() -> Self {
        Self {
            skill_tool_enabled: true,
            host_kind: DeveloperToolHarnessHostKind::Desktop,
        }
    }
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct DeveloperToolRuntimeCapabilitiesDto {
    pub browser_executor: bool,
    pub emulator_executor: bool,
    pub solana_executor: bool,
    pub skill_tool: bool,
    pub subagent_executor: bool,
    pub model_runner: bool,
}

impl DeveloperToolRuntimeCapabilitiesDto {
    fn terminal() -> Self {
        Self {
            browser_executor: false,
            emulator_executor: false,
            solana_executor: false,
            skill_tool: false,
            subagent_executor: false,
            model_runner: true,
        }
    }
}

#[derive(Debug, Clone)]
pub struct DeveloperToolTerminalHostContext {
    pub app_data_dir: PathBuf,
    pub global_db_path: PathBuf,
    pub project_id: String,
    pub repo_root: PathBuf,
    pub fixture_project: DeveloperToolHarnessProjectDto,
    pub capabilities: DeveloperToolRuntimeCapabilitiesDto,
}

pub fn developer_tool_catalog_service(
    options: DeveloperToolCatalogServiceOptions,
) -> CommandResult<DeveloperToolCatalogResponseDto> {
    let descriptor_schemas: HashMap<String, serde_json::Value> = builtin_tool_descriptors()
        .into_iter()
        .map(|descriptor| (descriptor.name, descriptor.input_schema))
        .collect();

    let entries = deferred_tool_catalog(options.skill_tool_enabled)
        .into_iter()
        .map(|entry| {
            let pack_ids = domain_tool_pack_ids_for_tool(entry.tool_name);
            let tool_packs = pack_ids
                .iter()
                .filter_map(|pack_id| {
                    domain_tool_pack_manifest(pack_id).map(|manifest| DeveloperToolPackSummaryDto {
                        pack_id: manifest.pack_id,
                        label: manifest.label,
                        policy_profile: manifest.policy_profile,
                    })
                })
                .collect();
            let (runtime_available, runtime_unavailable_reason) =
                runtime_availability_for_host(entry.tool_name, options.host_kind);
            DeveloperToolCatalogEntryDto {
                tool_name: entry.tool_name.to_owned(),
                group: entry.group.to_owned(),
                description: entry.description.to_owned(),
                tags: entry.tags.iter().map(|tag| (*tag).to_owned()).collect(),
                schema_fields: entry
                    .schema_fields
                    .iter()
                    .map(|field| (*field).to_owned())
                    .collect(),
                examples: entry
                    .examples
                    .iter()
                    .map(|example| (*example).to_owned())
                    .collect(),
                risk_class: entry.risk_class.to_owned(),
                effect_class: tool_effect_class(entry.tool_name).as_str().to_owned(),
                runtime_available,
                allowed_runtime_agents: allowed_runtime_agent_labels(entry.tool_name)
                    .into_iter()
                    .map(str::to_owned)
                    .collect(),
                activation_groups: tool_catalog_activation_groups(entry.tool_name),
                tool_packs,
                input_schema: descriptor_schemas.get(entry.tool_name).cloned(),
                runtime_unavailable_reason,
            }
        })
        .collect();

    let host = runtime_host_metadata();

    Ok(DeveloperToolCatalogResponseDto {
        host_os: host.operating_system,
        host_os_label: host.operating_system_label,
        skill_tool_enabled: options.skill_tool_enabled,
        entries,
    })
}

#[tauri::command]
pub fn developer_tool_catalog(
    request: Option<DeveloperToolCatalogRequestDto>,
) -> CommandResult<DeveloperToolCatalogResponseDto> {
    let request = request.unwrap_or_default();
    developer_tool_catalog_service(DeveloperToolCatalogServiceOptions {
        skill_tool_enabled: request.skill_tool_enabled.unwrap_or(true),
        host_kind: DeveloperToolHarnessHostKind::Desktop,
    })
}

pub fn terminal_runtime_unavailable_reason(tool_name: &str) -> Option<String> {
    let host = runtime_host_metadata();
    if !tool_available_on_current_host(tool_name) {
        return Some(format!(
            "`{tool_name}` is not available on {}.",
            host.operating_system_label
        ));
    }

    let pack_ids = domain_tool_pack_ids_for_tool(tool_name);
    if pack_ids.iter().any(|pack_id| pack_id == "browser") {
        return Some(
            "Browser tools require the Tauri desktop browser executor, which is not attached in terminal harness mode."
                .into(),
        );
    }
    if pack_ids.iter().any(|pack_id| pack_id == "emulator") {
        return Some(
            "Emulator tools require the Tauri desktop emulator executor, which is not attached in terminal harness mode."
                .into(),
        );
    }
    if pack_ids.iter().any(|pack_id| pack_id == "solana") {
        return Some(
            "Solana tools require the desktop Solana workbench state executor, which is not attached in terminal harness mode."
                .into(),
        );
    }

    match tool_effect_class(tool_name).as_str() {
        "skill_runtime" => Some(
            "The skill tool requires the desktop skill runtime cache/settings bridge, which is not attached in terminal harness mode."
                .into(),
        ),
        "agent_delegation" => Some(
            "Subagent delegation requires the desktop owned-agent runtime supervisor, which is not attached in terminal harness mode."
                .into(),
        ),
        _ => None,
    }
}

fn runtime_availability_for_host(
    tool_name: &str,
    host_kind: DeveloperToolHarnessHostKind,
) -> (bool, Option<String>) {
    match host_kind {
        DeveloperToolHarnessHostKind::Desktop => {
            if tool_available_on_current_host(tool_name) {
                (true, None)
            } else {
                let host = runtime_host_metadata();
                (
                    false,
                    Some(format!(
                        "`{tool_name}` is not available on {}.",
                        host.operating_system_label
                    )),
                )
            }
        }
        DeveloperToolHarnessHostKind::Terminal => {
            match terminal_runtime_unavailable_reason(tool_name) {
                Some(reason) => (false, Some(reason)),
                None => (true, None),
            }
        }
    }
}

pub fn ensure_terminal_tool_available(tool_name: &str) -> CommandResult<()> {
    if let Some(reason) = terminal_runtime_unavailable_reason(tool_name) {
        return Err(CommandError::user_fixable(
            "developer_tool_terminal_tool_unavailable",
            format!("Tool `{tool_name}` is unavailable in terminal harness mode: {reason}"),
        ));
    }
    Ok(())
}

const HARNESS_PROVIDER_ID: &str = "developer_harness";
const HARNESS_MODEL_ID: &str = "developer_harness";

pub fn developer_tool_synthetic_run_service(
    repo_root: &Path,
    tool_runtime: AutonomousToolRuntime,
    request: DeveloperToolSyntheticRunRequestDto,
) -> CommandResult<DeveloperToolSyntheticRunResponseDto> {
    validate_non_empty(&request.project_id, "projectId")?;
    if request.calls.is_empty() {
        return Err(CommandError::user_fixable(
            "developer_tool_harness_no_calls",
            "Synthetic harness runs require at least one tool call.",
        ));
    }

    let agent_session_id = match request.agent_session_id.as_deref() {
        Some(value) if !value.trim().is_empty() => value.trim().to_owned(),
        _ => {
            let session = project_store::create_agent_session(
                repo_root,
                &AgentSessionCreateRecord {
                    project_id: request.project_id.clone(),
                    title: format!("Tool harness — {}", now_timestamp()),
                    summary: "Created by the developer tool harness for synthetic dispatch.".into(),
                    selected: false,
                },
            )?;
            session.agent_session_id
        }
    };

    let run_id = generate_runtime_run_id();
    let calls = request
        .calls
        .into_iter()
        .map(|call| {
            let tool_name = call.tool_name.trim();
            if tool_name.is_empty() {
                return Err(CommandError::invalid_request("toolName"));
            }
            Ok(AgentToolCall {
                tool_call_id: call
                    .tool_call_id
                    .filter(|value| !value.trim().is_empty())
                    .unwrap_or_else(generate_tool_call_id),
                tool_name: tool_name.to_owned(),
                input: call.input,
            })
        })
        .collect::<CommandResult<Vec<_>>>()?;

    let options_dto = request.options.unwrap_or_default();
    let options = SyntheticDispatchOptions {
        stop_on_failure: options_dto.stop_on_failure.unwrap_or(true),
        approve_writes: options_dto.approve_writes.unwrap_or(false),
        operator_approve_all: options_dto.operator_approve_all.unwrap_or(false),
    };

    let outcome = dispatch_synthetic_tool_calls(
        repo_root,
        &request.project_id,
        agent_session_id,
        run_id,
        HARNESS_PROVIDER_ID.into(),
        HARNESS_MODEL_ID.into(),
        tool_runtime,
        calls,
        options,
    )?;

    Ok(DeveloperToolSyntheticRunResponseDto {
        run_id: outcome.run_id,
        agent_session_id: outcome.agent_session_id,
        stopped_early: outcome.stopped_early,
        had_failure: outcome.had_failure,
        results: outcome
            .results
            .into_iter()
            .map(|entry| DeveloperToolHarnessCallResultDto {
                tool_call_id: entry.tool_call_id,
                tool_name: entry.tool_name,
                ok: entry.ok,
                summary: entry.summary,
                output: entry.output,
            })
            .collect(),
    })
}

#[tauri::command]
pub fn developer_tool_synthetic_run<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolSyntheticRunRequestDto,
) -> CommandResult<DeveloperToolSyntheticRunResponseDto> {
    let repo_root = resolve_project_root(&app, state.inner(), &request.project_id)?;
    let tool_runtime =
        AutonomousToolRuntime::for_project(&app, state.inner(), &request.project_id)?;
    developer_tool_synthetic_run_service(&repo_root, tool_runtime, request)
}

pub fn developer_tool_dry_run_service(
    repo_root: &Path,
    tool_runtime: &AutonomousToolRuntime,
    request: DeveloperToolDryRunRequestDto,
) -> CommandResult<DeveloperToolDryRunResponseDto> {
    validate_non_empty(&request.project_id, "projectId")?;
    validate_non_empty(&request.tool_name, "toolName")?;

    let registry_options = ToolRegistryOptions {
        skill_tool_enabled: tool_runtime.skill_tool_enabled(),
        runtime_agent_id: RuntimeAgentIdDto::Engineer,
        ..ToolRegistryOptions::default()
    };
    let tool_registry = ToolRegistry::builtin_with_options(registry_options);

    let tool_call = AgentToolCall {
        tool_call_id: request
            .tool_call_id
            .filter(|value| !value.trim().is_empty())
            .unwrap_or_else(generate_tool_call_id),
        tool_name: request.tool_name,
        input: request.input,
    };
    let report = dry_run_tool_call(
        &tool_registry,
        tool_runtime,
        repo_root,
        &request.project_id,
        tool_call,
        request.operator_approved.unwrap_or(false),
    )?;

    Ok(DeveloperToolDryRunResponseDto {
        tool_call_id: report.tool_call_id,
        tool_name: report.tool_name,
        decoded: report.decoded,
        policy_decision: DeveloperToolPolicyDecisionDto {
            action: report.policy_decision.action.as_str().to_owned(),
            code: report.policy_decision.code,
            explanation: report.policy_decision.explanation,
            risk_class: report.policy_decision.risk_class,
            project_trust: report.policy_decision.project_trust,
            network_intent: report.policy_decision.network_intent,
            credential_sensitivity: report.policy_decision.credential_sensitivity,
            prior_observation_required: report.policy_decision.prior_observation_required,
            os_target: report.policy_decision.os_target,
        },
        sandbox_decision: report.sandbox_decision,
        sandbox_denied: report.sandbox_denied,
    })
}

#[tauri::command]
pub fn developer_tool_dry_run<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolDryRunRequestDto,
) -> CommandResult<DeveloperToolDryRunResponseDto> {
    let repo_root = resolve_project_root(&app, state.inner(), &request.project_id)?;
    let tool_runtime =
        AutonomousToolRuntime::for_project(&app, state.inner(), &request.project_id)?;
    developer_tool_dry_run_service(&repo_root, &tool_runtime, request)
}

fn generate_tool_call_id() -> String {
    let mut bytes = [0_u8; 8];
    rand::thread_rng().fill_bytes(&mut bytes);
    let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    format!("dev-harness-{hex}")
}

#[derive(serde::Serialize, serde::Deserialize)]
struct StoredSequencePayload {
    calls: Vec<DeveloperToolHarnessCallDto>,
    #[serde(default)]
    options: Option<DeveloperToolHarnessRunOptionsDto>,
}

fn generate_sequence_id() -> String {
    let mut bytes = [0_u8; 12];
    rand::thread_rng().fill_bytes(&mut bytes);
    let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    format!("dev-harness-seq-{hex}")
}

fn parse_stored_sequence(
    id: String,
    name: String,
    payload: &str,
    created_at: String,
    updated_at: String,
) -> CommandResult<DeveloperToolSequenceRecordDto> {
    let parsed: StoredSequencePayload = serde_json::from_str(payload).map_err(|error| {
        CommandError::system_fault(
            "developer_tool_sequence_payload_invalid",
            format!("Xero could not parse developer tool sequence `{id}` payload: {error}"),
        )
    })?;
    Ok(DeveloperToolSequenceRecordDto {
        id,
        name,
        calls: parsed.calls,
        options: parsed.options,
        created_at,
        updated_at,
    })
}

pub fn developer_tool_sequence_list_service(
    global_db_path: &Path,
) -> CommandResult<DeveloperToolSequenceListResponseDto> {
    let connection = open_global_database(global_db_path)?;
    let mut statement = connection
        .prepare(
            "SELECT id, name, payload, created_at, updated_at \
             FROM developer_tool_sequences \
             ORDER BY updated_at DESC, name ASC",
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_list_failed",
                format!("Xero could not prepare the developer tool sequence query: {error}"),
            )
        })?;
    let rows = statement
        .query_map([], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, String>(3)?,
                row.get::<_, String>(4)?,
            ))
        })
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_list_failed",
                format!("Xero could not list developer tool sequences: {error}"),
            )
        })?;

    let mut sequences = Vec::new();
    for row in rows {
        let (id, name, payload, created_at, updated_at) = row.map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_list_failed",
                format!("Xero could not read a developer tool sequence row: {error}"),
            )
        })?;
        sequences.push(parse_stored_sequence(
            id, name, &payload, created_at, updated_at,
        )?);
    }

    Ok(DeveloperToolSequenceListResponseDto { sequences })
}

#[tauri::command]
pub fn developer_tool_sequence_list<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
) -> CommandResult<DeveloperToolSequenceListResponseDto> {
    let global_db_path = state.global_db_path(&app)?;
    developer_tool_sequence_list_service(&global_db_path)
}

pub fn developer_tool_sequence_upsert_service(
    global_db_path: &Path,
    request: DeveloperToolSequenceUpsertRequestDto,
) -> CommandResult<DeveloperToolSequenceRecordDto> {
    let name = request.name.trim().to_owned();
    if name.is_empty() {
        return Err(CommandError::invalid_request("name"));
    }
    if request.calls.is_empty() {
        return Err(CommandError::user_fixable(
            "developer_tool_sequence_no_calls",
            "Sequences must contain at least one tool call.",
        ));
    }

    let id = request
        .id
        .clone()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
        .unwrap_or_else(generate_sequence_id);

    let payload = StoredSequencePayload {
        calls: request.calls.clone(),
        options: request.options.clone(),
    };
    let payload_json = serde_json::to_string(&payload).map_err(|error| {
        CommandError::system_fault(
            "developer_tool_sequence_payload_serialize_failed",
            format!("Xero could not serialize the developer tool sequence: {error}"),
        )
    })?;

    let connection = open_global_database(global_db_path)?;
    let now = now_timestamp();
    connection
        .execute(
            "INSERT INTO developer_tool_sequences (id, name, payload, created_at, updated_at) \
             VALUES (?1, ?2, ?3, ?4, ?4) \
             ON CONFLICT(id) DO UPDATE SET name = excluded.name, payload = excluded.payload, updated_at = excluded.updated_at",
            rusqlite::params![id, name, payload_json, now],
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_upsert_failed",
                format!("Xero could not upsert the developer tool sequence: {error}"),
            )
        })?;

    let (created_at, updated_at) = connection
        .query_row(
            "SELECT created_at, updated_at FROM developer_tool_sequences WHERE id = ?1",
            rusqlite::params![id],
            |row| Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?)),
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_read_back_failed",
                format!("Xero could not read back the upserted developer tool sequence: {error}"),
            )
        })?;

    Ok(DeveloperToolSequenceRecordDto {
        id,
        name,
        calls: request.calls,
        options: request.options,
        created_at,
        updated_at,
    })
}

#[tauri::command]
pub fn developer_tool_sequence_upsert<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolSequenceUpsertRequestDto,
) -> CommandResult<DeveloperToolSequenceRecordDto> {
    let global_db_path = state.global_db_path(&app)?;
    developer_tool_sequence_upsert_service(&global_db_path, request)
}

#[tauri::command]
pub fn developer_tool_model_run<R: Runtime + 'static>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolModelRunRequestDto,
) -> CommandResult<DeveloperToolModelRunResponseDto> {
    validate_non_empty(&request.project_id, "projectId")?;
    validate_non_empty(&request.tool_name, "toolName")?;
    validate_non_empty(&request.prompt, "prompt")?;

    let runtime_agent_id = match request.runtime_agent_id.as_deref() {
        None | Some("") | Some("engineer") => RuntimeAgentIdDto::Engineer,
        Some("ask") => RuntimeAgentIdDto::Ask,
        Some("plan") => RuntimeAgentIdDto::Plan,
        Some("crawl") => RuntimeAgentIdDto::Crawl,
        Some("debug") => RuntimeAgentIdDto::Debug,
        Some("agent_create") => RuntimeAgentIdDto::AgentCreate,
        Some("generalist") => RuntimeAgentIdDto::Generalist,
        Some(other) => {
            return Err(CommandError::user_fixable(
                "developer_tool_harness_invalid_agent",
                format!("Unknown runtime agent id `{other}`."),
            ));
        }
    };

    let repo_root = resolve_project_root(&app, state.inner(), &request.project_id)?;
    let agent_session_id = match request.agent_session_id.as_deref() {
        Some(value) if !value.trim().is_empty() => value.trim().to_owned(),
        _ => {
            let session = project_store::create_agent_session(
                &repo_root,
                &AgentSessionCreateRecord {
                    project_id: request.project_id.clone(),
                    title: format!("Tool harness (mode A) — {}", now_timestamp()),
                    summary: format!(
                        "Created by the developer tool harness to model-drive `{}`.",
                        request.tool_name
                    ),
                    selected: false,
                },
            )?;
            session.agent_session_id
        }
    };

    let prompt = format!(
        "Tool harness (mode A): exercise the `{}` tool. {}",
        request.tool_name, request.prompt,
    );

    let controls = RuntimeRunControlInputDto {
        runtime_agent_id,
        agent_definition_id: None,
        provider_profile_id: None,
        model_id: String::new(),
        thinking_effort: None,
        approval_mode: RuntimeRunApprovalModeDto::Suggest,
        plan_mode_required: false,
    };

    let snapshot = start_agent_task(
        app,
        state,
        StartAgentTaskRequestDto {
            project_id: request.project_id.clone(),
            agent_session_id: agent_session_id.clone(),
            prompt,
            controls: Some(controls),
        },
    )?;

    Ok(DeveloperToolModelRunResponseDto {
        run_id: snapshot.run_id,
        agent_session_id,
        project_id: request.project_id,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_returns_entries_with_schemas() {
        let response = developer_tool_catalog(None).expect("catalog returns ok");
        assert!(
            !response.entries.is_empty(),
            "catalog should return at least one entry"
        );
        assert!(
            response
                .entries
                .iter()
                .any(|entry| entry.tool_name == "read"),
            "catalog should include the read tool"
        );

        let read_entry = response
            .entries
            .iter()
            .find(|entry| entry.tool_name == "read")
            .expect("read entry");
        assert_eq!(read_entry.group, "core");
        assert_eq!(read_entry.effect_class, "observe");
        assert!(
            read_entry.input_schema.is_some(),
            "read should expose a schema"
        );
        assert!(
            !read_entry.allowed_runtime_agents.is_empty(),
            "read should be allowed for at least one runtime agent"
        );
    }

    #[test]
    fn catalog_skill_tool_filtering_respects_request() {
        let with_skill = developer_tool_catalog(Some(DeveloperToolCatalogRequestDto {
            skill_tool_enabled: Some(true),
        }))
        .expect("with skill");
        let without_skill = developer_tool_catalog(Some(DeveloperToolCatalogRequestDto {
            skill_tool_enabled: Some(false),
        }))
        .expect("without skill");
        let with_count = with_skill
            .entries
            .iter()
            .filter(|entry| entry.tool_name == "skill")
            .count();
        let without_count = without_skill
            .entries
            .iter()
            .filter(|entry| entry.tool_name == "skill")
            .count();
        assert_eq!(with_count, 1);
        assert_eq!(without_count, 0);
    }

    #[test]
    fn catalog_marks_host_unavailable_tools() {
        let response = developer_tool_catalog(None).expect("catalog");
        // macos_automation should be flagged on non-mac hosts
        if !cfg!(target_os = "macos") {
            assert!(
                response
                    .entries
                    .iter()
                    .any(|entry| entry.tool_name == "macos_automation" && !entry.runtime_available),
                "macos_automation should be marked unavailable on non-mac hosts"
            );
        }
    }

    #[test]
    fn catalog_service_matches_desktop_wrapper() {
        let wrapper = developer_tool_catalog(Some(DeveloperToolCatalogRequestDto {
            skill_tool_enabled: Some(false),
        }))
        .expect("wrapper catalog");
        let service = developer_tool_catalog_service(DeveloperToolCatalogServiceOptions {
            skill_tool_enabled: false,
            host_kind: DeveloperToolHarnessHostKind::Desktop,
        })
        .expect("service catalog");

        assert_eq!(service.entries, wrapper.entries);
        assert_eq!(service.skill_tool_enabled, wrapper.skill_tool_enabled);
    }

    #[test]
    fn fixture_service_seeds_app_data_project_and_registry() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let global_db_path = crate::global_db::global_database_path(tempdir.path());

        let project =
            prepare_harness_fixture_project(tempdir.path(), &global_db_path).expect("fixture");

        let root = PathBuf::from(&project.root_path);
        assert!(root.starts_with(tempdir.path()));
        assert!(!root
            .components()
            .any(|component| { component.as_os_str() == std::ffi::OsStr::new(".xero") }));
        assert_eq!(
            fs::read_to_string(root.join("sample.txt")).expect("sample"),
            HARNESS_FIXTURE_SAMPLE
        );
        let records = registry::read_project_records(&global_db_path, HARNESS_FIXTURE_PROJECT_ID)
            .expect("registry");
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].root_path, project.root_path);
    }

    #[test]
    fn sequence_service_validates_and_round_trips() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let global_db_path = crate::global_db::global_database_path(tempdir.path());
        let call = DeveloperToolHarnessCallDto {
            tool_name: "read".into(),
            input: serde_json::json!({"path": "README.md"}),
            tool_call_id: None,
        };

        let invalid_name = developer_tool_sequence_upsert_service(
            &global_db_path,
            DeveloperToolSequenceUpsertRequestDto {
                id: None,
                name: " ".into(),
                calls: vec![call.clone()],
                options: None,
            },
        )
        .expect_err("name validation");
        assert_eq!(invalid_name.code, "invalid_request");

        let invalid_calls = developer_tool_sequence_upsert_service(
            &global_db_path,
            DeveloperToolSequenceUpsertRequestDto {
                id: None,
                name: "empty".into(),
                calls: Vec::new(),
                options: None,
            },
        )
        .expect_err("call validation");
        assert_eq!(invalid_calls.code, "developer_tool_sequence_no_calls");

        let created = developer_tool_sequence_upsert_service(
            &global_db_path,
            DeveloperToolSequenceUpsertRequestDto {
                id: None,
                name: "smoke".into(),
                calls: vec![call.clone()],
                options: None,
            },
        )
        .expect("create");
        let updated = developer_tool_sequence_upsert_service(
            &global_db_path,
            DeveloperToolSequenceUpsertRequestDto {
                id: Some(created.id.clone()),
                name: "smoke updated".into(),
                calls: vec![call],
                options: Some(DeveloperToolHarnessRunOptionsDto {
                    stop_on_failure: Some(false),
                    approve_writes: Some(false),
                    operator_approve_all: Some(false),
                }),
            },
        )
        .expect("update");
        assert_eq!(created.id, updated.id);

        let list = developer_tool_sequence_list_service(&global_db_path).expect("list");
        assert_eq!(list.sequences.len(), 1);
        assert_eq!(list.sequences[0].name, "smoke updated");

        let deleted = developer_tool_sequence_delete_service(
            &global_db_path,
            DeveloperToolSequenceDeleteRequestDto { id: updated.id },
        )
        .expect("delete");
        assert!(deleted.sequences.is_empty());
    }

    #[test]
    fn terminal_catalog_marks_desktop_only_tools_with_reasons() {
        let response = developer_tool_catalog_service(DeveloperToolCatalogServiceOptions {
            skill_tool_enabled: false,
            host_kind: DeveloperToolHarnessHostKind::Terminal,
        })
        .expect("terminal catalog");
        let browser = response
            .entries
            .iter()
            .find(|entry| entry.tool_name == "browser_control")
            .expect("browser_control");

        assert!(!browser.runtime_available);
        assert!(browser
            .runtime_unavailable_reason
            .as_deref()
            .unwrap_or_default()
            .contains("Tauri desktop browser executor"));
    }

    #[test]
    fn terminal_dry_run_and_synthetic_read_smoke() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let context = developer_tool_terminal_host_context(tempdir.path()).expect("context");

        let dry_run = developer_tool_terminal_dry_run(
            &context,
            DeveloperToolDryRunRequestDto {
                project_id: context.project_id.clone(),
                tool_name: "read".into(),
                input: serde_json::json!({"path": "README.md"}),
                tool_call_id: None,
                operator_approved: Some(false),
            },
        )
        .expect("dry-run");
        assert_eq!(dry_run.tool_name, "read");
        assert!(dry_run.decoded);

        let run = developer_tool_terminal_synthetic_run(
            &context,
            DeveloperToolSyntheticRunRequestDto {
                project_id: context.project_id.clone(),
                agent_session_id: None,
                calls: vec![DeveloperToolHarnessCallDto {
                    tool_name: "read".into(),
                    input: serde_json::json!({"path": "README.md"}),
                    tool_call_id: None,
                }],
                options: Some(DeveloperToolHarnessRunOptionsDto {
                    stop_on_failure: Some(true),
                    approve_writes: Some(false),
                    operator_approve_all: Some(false),
                }),
            },
        )
        .expect("synthetic run");
        assert!(!run.had_failure, "{run:#?}");
        assert_eq!(run.results.len(), 1);
        assert!(run.results[0].ok, "{:#?}", run.results[0]);
    }

    #[test]
    fn synthetic_run_service_rejects_empty_calls() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let context = developer_tool_terminal_host_context(tempdir.path()).expect("context");
        let runtime = developer_tool_terminal_runtime(&context).expect("runtime");

        let error = developer_tool_synthetic_run_service(
            &context.repo_root,
            runtime,
            DeveloperToolSyntheticRunRequestDto {
                project_id: context.project_id.clone(),
                agent_session_id: None,
                calls: Vec::new(),
                options: None,
            },
        )
        .expect_err("empty calls rejected");

        assert_eq!(error.code, "developer_tool_harness_no_calls");
    }

    #[test]
    fn dry_run_invalid_payload_returns_decode_denial_shape() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let context = developer_tool_terminal_host_context(tempdir.path()).expect("context");

        let dry_run = developer_tool_terminal_dry_run(
            &context,
            DeveloperToolDryRunRequestDto {
                project_id: context.project_id.clone(),
                tool_name: "read".into(),
                input: serde_json::json!({}),
                tool_call_id: None,
                operator_approved: Some(false),
            },
        )
        .expect("dry-run returns structured denial");

        assert!(!dry_run.decoded);
        assert_eq!(dry_run.policy_decision.action, "deny");
        assert_eq!(
            dry_run.sandbox_decision,
            serde_json::json!({ "skipped": "policy_failed_to_decode" })
        );
    }

    #[test]
    fn synthetic_template_failure_reports_failing_token() {
        let tempdir = tempfile::tempdir().expect("tempdir");
        let context = developer_tool_terminal_host_context(tempdir.path()).expect("context");

        let run = developer_tool_terminal_synthetic_run(
            &context,
            DeveloperToolSyntheticRunRequestDto {
                project_id: context.project_id.clone(),
                agent_session_id: None,
                calls: vec![
                    DeveloperToolHarnessCallDto {
                        tool_name: "read".into(),
                        input: serde_json::json!({"path": "README.md"}),
                        tool_call_id: Some("first".into()),
                    },
                    DeveloperToolHarnessCallDto {
                        tool_name: "read".into(),
                        input: serde_json::json!({"path": "{{call[3].result.path}}"}),
                        tool_call_id: Some("second".into()),
                    },
                ],
                options: Some(DeveloperToolHarnessRunOptionsDto {
                    stop_on_failure: Some(true),
                    approve_writes: Some(false),
                    operator_approve_all: Some(false),
                }),
            },
        )
        .expect("template failure is a structured run result");

        assert!(run.had_failure);
        assert!(run.stopped_early);
        assert_eq!(run.results.len(), 2);
        assert_eq!(
            run.results[1].output["error"]["code"],
            serde_json::json!("developer_tool_harness_template_unresolved")
        );
        assert!(run.results[1].summary.contains("call[3]"));
    }

    #[test]
    fn terminal_rejects_unavailable_tools_before_dispatch() {
        let error = ensure_terminal_tool_available("browser_control").expect_err("unavailable");

        assert_eq!(error.code, "developer_tool_terminal_tool_unavailable");
        assert!(error.message.contains("terminal harness mode"));
    }
}

#[tauri::command]
pub fn developer_tool_sequence_delete<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolSequenceDeleteRequestDto,
) -> CommandResult<DeveloperToolSequenceListResponseDto> {
    let global_db_path = state.global_db_path(&app)?;
    developer_tool_sequence_delete_service(&global_db_path, request)
}

pub fn developer_tool_sequence_delete_service(
    global_db_path: &Path,
    request: DeveloperToolSequenceDeleteRequestDto,
) -> CommandResult<DeveloperToolSequenceListResponseDto> {
    validate_non_empty(&request.id, "id")?;
    let connection = open_global_database(global_db_path)?;
    connection
        .execute(
            "DELETE FROM developer_tool_sequences WHERE id = ?1",
            rusqlite::params![request.id],
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_delete_failed",
                format!("Xero could not delete the developer tool sequence: {error}"),
            )
        })?;

    developer_tool_sequence_list_service(global_db_path)
}

#[tauri::command]
pub fn developer_tool_harness_project<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
) -> CommandResult<DeveloperToolHarnessProjectDto> {
    let registry_path = state.global_db_path(&app)?;
    let app_data_dir = state.app_data_dir(&app)?;
    prepare_harness_fixture_project(&app_data_dir, &registry_path)
}

pub fn prepare_harness_fixture_project(
    app_data_dir: &Path,
    global_db_path: &Path,
) -> CommandResult<DeveloperToolHarnessProjectDto> {
    let repo_root = app_data_dir.join(HARNESS_FIXTURE_DIRECTORY);

    seed_harness_fixture_repo(&repo_root)?;
    ensure_harness_fixture_registered(global_db_path, &repo_root)?;

    Ok(DeveloperToolHarnessProjectDto {
        project_id: HARNESS_FIXTURE_PROJECT_ID.to_owned(),
        display_name: HARNESS_FIXTURE_DISPLAY_NAME.to_owned(),
        root_path: repo_root.to_string_lossy().into_owned(),
    })
}

pub fn developer_tool_terminal_host_context(
    app_data_dir: impl AsRef<Path>,
) -> CommandResult<DeveloperToolTerminalHostContext> {
    let app_data_dir = app_data_dir.as_ref().to_path_buf();
    reject_legacy_xero_state_path(&app_data_dir, "app-data root")?;
    let global_db_path = crate::global_db::global_database_path(&app_data_dir);
    let fixture_project = prepare_harness_fixture_project(&app_data_dir, &global_db_path)?;
    let records = registry::read_project_records(&global_db_path, HARNESS_FIXTURE_PROJECT_ID)?;
    let record = records.into_iter().next().ok_or_else(|| {
        CommandError::system_fault(
            "developer_tool_terminal_fixture_registry_missing",
            "Xero prepared the harness fixture project but could not find it in the app-data registry.",
        )
    })?;
    let repo_root = PathBuf::from(record.root_path);
    if !repo_root.is_dir() {
        return Err(CommandError::user_fixable(
            "developer_tool_terminal_fixture_root_missing",
            format!(
                "The harness fixture project root `{}` is missing.",
                repo_root.display()
            ),
        ));
    }
    db::configure_project_database_paths(&global_db_path);
    Ok(DeveloperToolTerminalHostContext {
        app_data_dir,
        global_db_path,
        project_id: HARNESS_FIXTURE_PROJECT_ID.to_owned(),
        repo_root,
        fixture_project,
        capabilities: DeveloperToolRuntimeCapabilitiesDto::terminal(),
    })
}

pub fn developer_tool_terminal_runtime(
    context: &DeveloperToolTerminalHostContext,
) -> CommandResult<AutonomousToolRuntime> {
    db::configure_project_database_paths(&context.global_db_path);
    AutonomousToolRuntime::new(&context.repo_root).map(|runtime| {
        runtime
            .with_mcp_registry_path(context.global_db_path.clone())
            .with_environment_profile_database_path(context.global_db_path.clone())
            .with_skill_tool_disabled()
    })
}

pub fn developer_tool_terminal_dry_run(
    context: &DeveloperToolTerminalHostContext,
    request: DeveloperToolDryRunRequestDto,
) -> CommandResult<DeveloperToolDryRunResponseDto> {
    ensure_terminal_tool_available(&request.tool_name)?;
    let runtime = developer_tool_terminal_runtime(context)?;
    developer_tool_dry_run_service(&context.repo_root, &runtime, request)
}

pub fn developer_tool_terminal_synthetic_run(
    context: &DeveloperToolTerminalHostContext,
    request: DeveloperToolSyntheticRunRequestDto,
) -> CommandResult<DeveloperToolSyntheticRunResponseDto> {
    for call in &request.calls {
        ensure_terminal_tool_available(&call.tool_name)?;
    }
    let runtime = developer_tool_terminal_runtime(context)?;
    developer_tool_synthetic_run_service(&context.repo_root, runtime, request)
}

fn reject_legacy_xero_state_path(path: &Path, label: &str) -> CommandResult<()> {
    if path
        .components()
        .any(|component| component.as_os_str() == std::ffi::OsStr::new(".xero"))
    {
        return Err(CommandError::user_fixable(
            "developer_tool_legacy_state_path_rejected",
            format!(
                "The developer tool harness cannot use repo-local `.xero` state for {label}: {}",
                path.display()
            ),
        ));
    }
    Ok(())
}

fn seed_harness_fixture_repo(repo_root: &Path) -> CommandResult<()> {
    fs::create_dir_all(repo_root).map_err(|error| {
        CommandError::system_fault(
            "developer_tool_harness_fixture_dir_failed",
            format!(
                "Xero could not create the harness fixture directory at {}: {error}",
                repo_root.display()
            ),
        )
    })?;

    write_fixture_file(repo_root, "README.md", HARNESS_FIXTURE_README)?;
    write_fixture_file(repo_root, "sample.txt", HARNESS_FIXTURE_SAMPLE)?;

    Ok(())
}

fn write_fixture_file(repo_root: &Path, relative: &str, contents: &str) -> CommandResult<()> {
    let path = repo_root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            CommandError::system_fault(
                "developer_tool_harness_fixture_dir_failed",
                format!(
                    "Xero could not create the harness fixture parent at {}: {error}",
                    parent.display()
                ),
            )
        })?;
    }

    let needs_write = match fs::read_to_string(&path) {
        Ok(existing) => existing != contents,
        Err(_) => true,
    };

    if needs_write {
        fs::write(&path, contents).map_err(|error| {
            CommandError::system_fault(
                "developer_tool_harness_fixture_seed_failed",
                format!(
                    "Xero could not seed the harness fixture file at {}: {error}",
                    path.display()
                ),
            )
        })?;
    }

    Ok(())
}

fn ensure_harness_fixture_registered(
    registry_path: &Path,
    repo_root: &Path,
) -> CommandResult<PathBuf> {
    db::configure_project_database_paths(registry_path);

    let root_path_string = repo_root.to_string_lossy().into_owned();
    let repository = CanonicalRepository {
        project_id: HARNESS_FIXTURE_PROJECT_ID.to_owned(),
        repository_id: HARNESS_FIXTURE_REPOSITORY_ID.to_owned(),
        root_path: repo_root.to_path_buf(),
        root_path_string: root_path_string.clone(),
        common_git_dir: repo_root.join(".git"),
        display_name: HARNESS_FIXTURE_DISPLAY_NAME.to_owned(),
        branch_name: None,
        head_sha: None,
        branch: None,
        last_commit: None,
        status_entries: Vec::new(),
        has_staged_changes: false,
        has_unstaged_changes: false,
        has_untracked_changes: false,
        additions: 0,
        deletions: 0,
    };

    let imported = db::import_project_with_origin(
        &repository,
        ProjectOrigin::Greenfield,
        &Default::default(),
    )?;

    registry::upsert_project(
        registry_path,
        RegistryProjectRecord {
            project_id: imported.project.id.clone(),
            repository_id: imported.repository.id.clone(),
            root_path: imported.repository.root_path.clone(),
        },
        &Default::default(),
    )?;

    Ok(repo_root.to_path_buf())
}
