use std::{
    collections::HashMap,
    fs,
    path::{Path, PathBuf},
};

use rand::RngCore;
use serde::Deserialize;
use tauri::{AppHandle, Runtime, State};

use crate::{
    auth::now_timestamp,
    commands::{
        contracts::developer_tool_harness::{
            DeveloperToolCatalogEntryDto, DeveloperToolCatalogResponseDto,
            DeveloperToolDryRunRequestDto, DeveloperToolDryRunResponseDto,
            DeveloperToolHarnessCallDto, DeveloperToolHarnessCallResultDto,
            DeveloperToolHarnessProjectDto, DeveloperToolHarnessRunOptionsDto,
            DeveloperToolModelRunRequestDto, DeveloperToolModelRunResponseDto,
            DeveloperToolPackSummaryDto, DeveloperToolPolicyDecisionDto,
            DeveloperToolSequenceDeleteRequestDto, DeveloperToolSequenceListResponseDto,
            DeveloperToolSequenceRecordDto, DeveloperToolSequenceUpsertRequestDto,
            DeveloperToolSyntheticRunRequestDto, DeveloperToolSyntheticRunResponseDto,
        },
        start_agent_task, validate_non_empty, CommandError, CommandResult, RuntimeAgentIdDto,
        RuntimeRunApprovalModeDto, RuntimeRunControlInputDto, StartAgentTaskRequestDto,
    },
    db::{self, project_store::{self, AgentSessionCreateRecord}, ProjectOrigin},
    git::repository::CanonicalRepository,
    global_db::open_global_database,
    registry::{self, RegistryProjectRecord},
    runtime::agent_core::{
        builtin_tool_descriptors, dispatch_synthetic_tool_calls, dry_run_tool_call, AgentToolCall,
        SyntheticDispatchOptions, ToolRegistry, ToolRegistryOptions,
    },
    runtime::autonomous_tool_runtime::{
        allowed_runtime_agent_labels, deferred_tool_catalog, runtime_host_metadata,
        tool_available_on_current_host, tool_catalog_activation_groups, tool_effect_class,
        AutonomousToolRuntime,
    },
    state::DesktopState,
};
use xero_agent_core::{domain_tool_pack_ids_for_tool, domain_tool_pack_manifest};

use super::runtime_support::{generate_runtime_run_id, resolve_project_root};

pub const HARNESS_FIXTURE_PROJECT_ID: &str = "xero-developer-tool-harness-fixture";
const HARNESS_FIXTURE_REPOSITORY_ID: &str = "xero-developer-tool-harness-fixture-repo";
const HARNESS_FIXTURE_DISPLAY_NAME: &str = "Tool harness fixture";
const HARNESS_FIXTURE_DIRECTORY: &str = "developer-tool-harness/fixture";
const HARNESS_FIXTURE_README: &str = "# Tool harness fixture\n\nThis repository is auto-generated by Xero so the developer tool harness has a stable, isolated project to exercise tools against. Files here are deterministic and replaced whenever the harness needs them — do not store anything important in this folder.\n";
const HARNESS_FIXTURE_SAMPLE: &str = "alpha\nbeta\ngamma\n";

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DeveloperToolCatalogRequestDto {
    #[serde(default)]
    pub skill_tool_enabled: Option<bool>,
}

#[tauri::command]
pub fn developer_tool_catalog(
    request: Option<DeveloperToolCatalogRequestDto>,
) -> CommandResult<DeveloperToolCatalogResponseDto> {
    let request = request.unwrap_or_default();
    let skill_tool_enabled = request.skill_tool_enabled.unwrap_or(true);

    let descriptor_schemas: HashMap<String, serde_json::Value> = builtin_tool_descriptors()
        .into_iter()
        .map(|descriptor| (descriptor.name, descriptor.input_schema))
        .collect();

    let entries = deferred_tool_catalog(skill_tool_enabled)
        .into_iter()
        .map(|entry| {
            let pack_ids = domain_tool_pack_ids_for_tool(entry.tool_name);
            let tool_packs = pack_ids
                .iter()
                .filter_map(|pack_id| {
                    domain_tool_pack_manifest(pack_id).map(|manifest| {
                        DeveloperToolPackSummaryDto {
                            pack_id: manifest.pack_id,
                            label: manifest.label,
                            policy_profile: manifest.policy_profile,
                        }
                    })
                })
                .collect();
            DeveloperToolCatalogEntryDto {
                tool_name: entry.tool_name.to_owned(),
                group: entry.group.to_owned(),
                description: entry.description.to_owned(),
                tags: entry.tags.iter().map(|tag| (*tag).to_owned()).collect(),
                schema_fields: entry
                    .schema_fields
                    .iter()
                    .map(|field| (*field).to_owned())
                    .collect(),
                examples: entry
                    .examples
                    .iter()
                    .map(|example| (*example).to_owned())
                    .collect(),
                risk_class: entry.risk_class.to_owned(),
                effect_class: tool_effect_class(entry.tool_name).as_str().to_owned(),
                runtime_available: tool_available_on_current_host(entry.tool_name),
                allowed_runtime_agents: allowed_runtime_agent_labels(entry.tool_name)
                    .into_iter()
                    .map(str::to_owned)
                    .collect(),
                activation_groups: tool_catalog_activation_groups(entry.tool_name),
                tool_packs,
                input_schema: descriptor_schemas.get(entry.tool_name).cloned(),
            }
        })
        .collect();

    let host = runtime_host_metadata();

    Ok(DeveloperToolCatalogResponseDto {
        host_os: host.operating_system,
        host_os_label: host.operating_system_label,
        skill_tool_enabled,
        entries,
    })
}

const HARNESS_PROVIDER_ID: &str = "developer_harness";
const HARNESS_MODEL_ID: &str = "developer_harness";

#[tauri::command]
pub fn developer_tool_synthetic_run<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolSyntheticRunRequestDto,
) -> CommandResult<DeveloperToolSyntheticRunResponseDto> {
    validate_non_empty(&request.project_id, "projectId")?;
    if request.calls.is_empty() {
        return Err(CommandError::user_fixable(
            "developer_tool_harness_no_calls",
            "Synthetic harness runs require at least one tool call.",
        ));
    }

    let repo_root = resolve_project_root(&app, state.inner(), &request.project_id)?;
    let tool_runtime = AutonomousToolRuntime::for_project(&app, state.inner(), &request.project_id)?;

    let agent_session_id = match request.agent_session_id.as_deref() {
        Some(value) if !value.trim().is_empty() => value.trim().to_owned(),
        _ => {
            let session = project_store::create_agent_session(
                &repo_root,
                &AgentSessionCreateRecord {
                    project_id: request.project_id.clone(),
                    title: format!("Tool harness — {}", now_timestamp()),
                    summary: "Created by the developer tool harness for synthetic dispatch."
                        .into(),
                    selected: false,
                },
            )?;
            session.agent_session_id
        }
    };

    let run_id = generate_runtime_run_id();
    let calls = request
        .calls
        .into_iter()
        .map(|call| {
            let tool_name = call.tool_name.trim();
            if tool_name.is_empty() {
                return Err(CommandError::invalid_request("toolName"));
            }
            Ok(AgentToolCall {
                tool_call_id: call
                    .tool_call_id
                    .filter(|value| !value.trim().is_empty())
                    .unwrap_or_else(generate_tool_call_id),
                tool_name: tool_name.to_owned(),
                input: call.input,
            })
        })
        .collect::<CommandResult<Vec<_>>>()?;

    let options_dto = request.options.unwrap_or_default();
    let options = SyntheticDispatchOptions {
        stop_on_failure: options_dto.stop_on_failure.unwrap_or(true),
        approve_writes: options_dto.approve_writes.unwrap_or(false),
        operator_approve_all: options_dto.operator_approve_all.unwrap_or(false),
    };

    let outcome = dispatch_synthetic_tool_calls(
        &repo_root,
        &request.project_id,
        agent_session_id,
        run_id,
        HARNESS_PROVIDER_ID.into(),
        HARNESS_MODEL_ID.into(),
        tool_runtime,
        calls,
        options,
    )?;

    Ok(DeveloperToolSyntheticRunResponseDto {
        run_id: outcome.run_id,
        agent_session_id: outcome.agent_session_id,
        stopped_early: outcome.stopped_early,
        had_failure: outcome.had_failure,
        results: outcome
            .results
            .into_iter()
            .map(|entry| DeveloperToolHarnessCallResultDto {
                tool_call_id: entry.tool_call_id,
                tool_name: entry.tool_name,
                ok: entry.ok,
                summary: entry.summary,
                output: entry.output,
            })
            .collect(),
    })
}

#[tauri::command]
pub fn developer_tool_dry_run<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolDryRunRequestDto,
) -> CommandResult<DeveloperToolDryRunResponseDto> {
    validate_non_empty(&request.project_id, "projectId")?;
    validate_non_empty(&request.tool_name, "toolName")?;

    let repo_root = resolve_project_root(&app, state.inner(), &request.project_id)?;
    let tool_runtime = AutonomousToolRuntime::for_project(&app, state.inner(), &request.project_id)?;
    let registry_options = ToolRegistryOptions {
        skill_tool_enabled: tool_runtime.skill_tool_enabled(),
        runtime_agent_id: RuntimeAgentIdDto::Engineer,
        ..ToolRegistryOptions::default()
    };
    let tool_registry = ToolRegistry::builtin_with_options(registry_options);

    let tool_call = AgentToolCall {
        tool_call_id: request
            .tool_call_id
            .filter(|value| !value.trim().is_empty())
            .unwrap_or_else(generate_tool_call_id),
        tool_name: request.tool_name,
        input: request.input,
    };
    let report = dry_run_tool_call(
        &tool_registry,
        &tool_runtime,
        &repo_root,
        &request.project_id,
        tool_call,
        request.operator_approved.unwrap_or(false),
    )?;

    Ok(DeveloperToolDryRunResponseDto {
        tool_call_id: report.tool_call_id,
        tool_name: report.tool_name,
        decoded: report.decoded,
        policy_decision: DeveloperToolPolicyDecisionDto {
            action: report.policy_decision.action.as_str().to_owned(),
            code: report.policy_decision.code,
            explanation: report.policy_decision.explanation,
            risk_class: report.policy_decision.risk_class,
            project_trust: report.policy_decision.project_trust,
            network_intent: report.policy_decision.network_intent,
            credential_sensitivity: report.policy_decision.credential_sensitivity,
            prior_observation_required: report.policy_decision.prior_observation_required,
            os_target: report.policy_decision.os_target,
        },
        sandbox_decision: report.sandbox_decision,
        sandbox_denied: report.sandbox_denied,
    })
}

fn generate_tool_call_id() -> String {
    let mut bytes = [0_u8; 8];
    rand::thread_rng().fill_bytes(&mut bytes);
    let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    format!("dev-harness-{hex}")
}

#[derive(serde::Serialize, serde::Deserialize)]
struct StoredSequencePayload {
    calls: Vec<DeveloperToolHarnessCallDto>,
    #[serde(default)]
    options: Option<DeveloperToolHarnessRunOptionsDto>,
}

fn generate_sequence_id() -> String {
    let mut bytes = [0_u8; 12];
    rand::thread_rng().fill_bytes(&mut bytes);
    let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    format!("dev-harness-seq-{hex}")
}

fn parse_stored_sequence(
    id: String,
    name: String,
    payload: &str,
    created_at: String,
    updated_at: String,
) -> CommandResult<DeveloperToolSequenceRecordDto> {
    let parsed: StoredSequencePayload = serde_json::from_str(payload).map_err(|error| {
        CommandError::system_fault(
            "developer_tool_sequence_payload_invalid",
            format!("Xero could not parse developer tool sequence `{id}` payload: {error}"),
        )
    })?;
    Ok(DeveloperToolSequenceRecordDto {
        id,
        name,
        calls: parsed.calls,
        options: parsed.options,
        created_at,
        updated_at,
    })
}

#[tauri::command]
pub fn developer_tool_sequence_list<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
) -> CommandResult<DeveloperToolSequenceListResponseDto> {
    let global_db_path = state.global_db_path(&app)?;
    let connection = open_global_database(&global_db_path)?;
    let mut statement = connection
        .prepare(
            "SELECT id, name, payload, created_at, updated_at \
             FROM developer_tool_sequences \
             ORDER BY updated_at DESC, name ASC",
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_list_failed",
                format!("Xero could not prepare the developer tool sequence query: {error}"),
            )
        })?;
    let rows = statement
        .query_map([], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
                row.get::<_, String>(3)?,
                row.get::<_, String>(4)?,
            ))
        })
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_list_failed",
                format!("Xero could not list developer tool sequences: {error}"),
            )
        })?;

    let mut sequences = Vec::new();
    for row in rows {
        let (id, name, payload, created_at, updated_at) = row.map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_list_failed",
                format!("Xero could not read a developer tool sequence row: {error}"),
            )
        })?;
        sequences.push(parse_stored_sequence(id, name, &payload, created_at, updated_at)?);
    }

    Ok(DeveloperToolSequenceListResponseDto { sequences })
}

#[tauri::command]
pub fn developer_tool_sequence_upsert<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolSequenceUpsertRequestDto,
) -> CommandResult<DeveloperToolSequenceRecordDto> {
    let name = request.name.trim().to_owned();
    if name.is_empty() {
        return Err(CommandError::invalid_request("name"));
    }
    if request.calls.is_empty() {
        return Err(CommandError::user_fixable(
            "developer_tool_sequence_no_calls",
            "Sequences must contain at least one tool call.",
        ));
    }

    let id = request
        .id
        .clone()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
        .unwrap_or_else(generate_sequence_id);

    let payload = StoredSequencePayload {
        calls: request.calls.clone(),
        options: request.options.clone(),
    };
    let payload_json = serde_json::to_string(&payload).map_err(|error| {
        CommandError::system_fault(
            "developer_tool_sequence_payload_serialize_failed",
            format!("Xero could not serialize the developer tool sequence: {error}"),
        )
    })?;

    let global_db_path = state.global_db_path(&app)?;
    let connection = open_global_database(&global_db_path)?;
    let now = now_timestamp();
    connection
        .execute(
            "INSERT INTO developer_tool_sequences (id, name, payload, created_at, updated_at) \
             VALUES (?1, ?2, ?3, ?4, ?4) \
             ON CONFLICT(id) DO UPDATE SET name = excluded.name, payload = excluded.payload, updated_at = excluded.updated_at",
            rusqlite::params![id, name, payload_json, now],
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_upsert_failed",
                format!("Xero could not upsert the developer tool sequence: {error}"),
            )
        })?;

    let (created_at, updated_at) = connection
        .query_row(
            "SELECT created_at, updated_at FROM developer_tool_sequences WHERE id = ?1",
            rusqlite::params![id],
            |row| Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?)),
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_read_back_failed",
                format!("Xero could not read back the upserted developer tool sequence: {error}"),
            )
        })?;

    Ok(DeveloperToolSequenceRecordDto {
        id,
        name,
        calls: request.calls,
        options: request.options,
        created_at,
        updated_at,
    })
}

#[tauri::command]
pub fn developer_tool_model_run<R: Runtime + 'static>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolModelRunRequestDto,
) -> CommandResult<DeveloperToolModelRunResponseDto> {
    validate_non_empty(&request.project_id, "projectId")?;
    validate_non_empty(&request.tool_name, "toolName")?;
    validate_non_empty(&request.prompt, "prompt")?;

    let runtime_agent_id = match request.runtime_agent_id.as_deref() {
        None | Some("") | Some("engineer") => RuntimeAgentIdDto::Engineer,
        Some("ask") => RuntimeAgentIdDto::Ask,
        Some("plan") => RuntimeAgentIdDto::Plan,
        Some("crawl") => RuntimeAgentIdDto::Crawl,
        Some("debug") => RuntimeAgentIdDto::Debug,
        Some("agent_create") => RuntimeAgentIdDto::AgentCreate,
        Some(other) => {
            return Err(CommandError::user_fixable(
                "developer_tool_harness_invalid_agent",
                format!("Unknown runtime agent id `{other}`."),
            ));
        }
    };

    let repo_root = resolve_project_root(&app, state.inner(), &request.project_id)?;
    let agent_session_id = match request.agent_session_id.as_deref() {
        Some(value) if !value.trim().is_empty() => value.trim().to_owned(),
        _ => {
            let session = project_store::create_agent_session(
                &repo_root,
                &AgentSessionCreateRecord {
                    project_id: request.project_id.clone(),
                    title: format!("Tool harness (mode A) — {}", now_timestamp()),
                    summary: format!(
                        "Created by the developer tool harness to model-drive `{}`.",
                        request.tool_name
                    ),
                    selected: false,
                },
            )?;
            session.agent_session_id
        }
    };

    let prompt = format!(
        "Tool harness (mode A): exercise the `{}` tool. {}",
        request.tool_name, request.prompt,
    );

    let controls = RuntimeRunControlInputDto {
        runtime_agent_id,
        agent_definition_id: None,
        provider_profile_id: None,
        model_id: String::new(),
        thinking_effort: None,
        approval_mode: RuntimeRunApprovalModeDto::Suggest,
        plan_mode_required: false,
    };

    let snapshot = start_agent_task(
        app,
        state,
        StartAgentTaskRequestDto {
            project_id: request.project_id.clone(),
            agent_session_id: agent_session_id.clone(),
            prompt,
            controls: Some(controls),
        },
    )?;

    Ok(DeveloperToolModelRunResponseDto {
        run_id: snapshot.run_id,
        agent_session_id,
        project_id: request.project_id,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_returns_entries_with_schemas() {
        let response = developer_tool_catalog(None).expect("catalog returns ok");
        assert!(
            !response.entries.is_empty(),
            "catalog should return at least one entry"
        );
        assert!(
            response
                .entries
                .iter()
                .any(|entry| entry.tool_name == "read"),
            "catalog should include the read tool"
        );

        let read_entry = response
            .entries
            .iter()
            .find(|entry| entry.tool_name == "read")
            .expect("read entry");
        assert_eq!(read_entry.group, "core");
        assert_eq!(read_entry.effect_class, "observe");
        assert!(read_entry.input_schema.is_some(), "read should expose a schema");
        assert!(
            !read_entry.allowed_runtime_agents.is_empty(),
            "read should be allowed for at least one runtime agent"
        );
    }

    #[test]
    fn catalog_skill_tool_filtering_respects_request() {
        let with_skill = developer_tool_catalog(Some(DeveloperToolCatalogRequestDto {
            skill_tool_enabled: Some(true),
        }))
        .expect("with skill");
        let without_skill = developer_tool_catalog(Some(DeveloperToolCatalogRequestDto {
            skill_tool_enabled: Some(false),
        }))
        .expect("without skill");
        let with_count = with_skill
            .entries
            .iter()
            .filter(|entry| entry.tool_name == "skill")
            .count();
        let without_count = without_skill
            .entries
            .iter()
            .filter(|entry| entry.tool_name == "skill")
            .count();
        assert_eq!(with_count, 1);
        assert_eq!(without_count, 0);
    }

    #[test]
    fn catalog_marks_host_unavailable_tools() {
        let response = developer_tool_catalog(None).expect("catalog");
        // macos_automation should be flagged on non-mac hosts
        if !cfg!(target_os = "macos") {
            assert!(
                response
                    .entries
                    .iter()
                    .any(|entry| entry.tool_name == "macos_automation" && !entry.runtime_available),
                "macos_automation should be marked unavailable on non-mac hosts"
            );
        }
    }
}

#[tauri::command]
pub fn developer_tool_sequence_delete<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
    request: DeveloperToolSequenceDeleteRequestDto,
) -> CommandResult<DeveloperToolSequenceListResponseDto> {
    validate_non_empty(&request.id, "id")?;
    let global_db_path = state.global_db_path(&app)?;
    let connection = open_global_database(&global_db_path)?;
    connection
        .execute(
            "DELETE FROM developer_tool_sequences WHERE id = ?1",
            rusqlite::params![request.id],
        )
        .map_err(|error| {
            CommandError::system_fault(
                "developer_tool_sequence_delete_failed",
                format!("Xero could not delete the developer tool sequence: {error}"),
            )
        })?;

    developer_tool_sequence_list(app, state)
}

#[tauri::command]
pub fn developer_tool_harness_project<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, DesktopState>,
) -> CommandResult<DeveloperToolHarnessProjectDto> {
    let registry_path = state.global_db_path(&app)?;
    let app_data_dir = state.app_data_dir(&app)?;
    let repo_root = app_data_dir.join(HARNESS_FIXTURE_DIRECTORY);

    seed_harness_fixture_repo(&repo_root)?;
    ensure_harness_fixture_registered(&registry_path, &repo_root)?;

    Ok(DeveloperToolHarnessProjectDto {
        project_id: HARNESS_FIXTURE_PROJECT_ID.to_owned(),
        display_name: HARNESS_FIXTURE_DISPLAY_NAME.to_owned(),
        root_path: repo_root.to_string_lossy().into_owned(),
    })
}

fn seed_harness_fixture_repo(repo_root: &Path) -> CommandResult<()> {
    fs::create_dir_all(repo_root).map_err(|error| {
        CommandError::system_fault(
            "developer_tool_harness_fixture_dir_failed",
            format!(
                "Xero could not create the harness fixture directory at {}: {error}",
                repo_root.display()
            ),
        )
    })?;

    write_fixture_file(repo_root, "README.md", HARNESS_FIXTURE_README)?;
    write_fixture_file(repo_root, "sample.txt", HARNESS_FIXTURE_SAMPLE)?;

    Ok(())
}

fn write_fixture_file(repo_root: &Path, relative: &str, contents: &str) -> CommandResult<()> {
    let path = repo_root.join(relative);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            CommandError::system_fault(
                "developer_tool_harness_fixture_dir_failed",
                format!(
                    "Xero could not create the harness fixture parent at {}: {error}",
                    parent.display()
                ),
            )
        })?;
    }

    let needs_write = match fs::read_to_string(&path) {
        Ok(existing) => existing != contents,
        Err(_) => true,
    };

    if needs_write {
        fs::write(&path, contents).map_err(|error| {
            CommandError::system_fault(
                "developer_tool_harness_fixture_seed_failed",
                format!(
                    "Xero could not seed the harness fixture file at {}: {error}",
                    path.display()
                ),
            )
        })?;
    }

    Ok(())
}

fn ensure_harness_fixture_registered(
    registry_path: &Path,
    repo_root: &Path,
) -> CommandResult<PathBuf> {
    db::configure_project_database_paths(registry_path);

    let root_path_string = repo_root.to_string_lossy().into_owned();
    let repository = CanonicalRepository {
        project_id: HARNESS_FIXTURE_PROJECT_ID.to_owned(),
        repository_id: HARNESS_FIXTURE_REPOSITORY_ID.to_owned(),
        root_path: repo_root.to_path_buf(),
        root_path_string: root_path_string.clone(),
        common_git_dir: repo_root.join(".git"),
        display_name: HARNESS_FIXTURE_DISPLAY_NAME.to_owned(),
        branch_name: None,
        head_sha: None,
        branch: None,
        last_commit: None,
        status_entries: Vec::new(),
        has_staged_changes: false,
        has_unstaged_changes: false,
        has_untracked_changes: false,
        additions: 0,
        deletions: 0,
    };

    let imported = db::import_project_with_origin(
        &repository,
        ProjectOrigin::Greenfield,
        &Default::default(),
    )?;

    registry::upsert_project(
        registry_path,
        RegistryProjectRecord {
            project_id: imported.project.id.clone(),
            repository_id: imported.repository.id.clone(),
            root_path: imported.repository.root_path.clone(),
        },
        &Default::default(),
    )?;

    Ok(repo_root.to_path_buf())
}
