//! Carbon indexer scaffold renderer.
//!
//! Produces a compilable Rust binary crate with:
//! - `Cargo.toml`  — pinned Carbon + solana-client deps.
//! - `src/main.rs` — a tokio main that subscribes to the program's
//!   signatures via Carbon's RPC processor and decodes Anchor events
//!   using the IDL discriminators baked into `events.rs`.
//! - `src/events.rs` — const arrays of `(name, discriminator)` pairs.
//! - `idl/program.json` — the IDL itself (consumed at runtime).
//! - `README.md` — run instructions.
//! - `.gitignore` — standard cargo ignores.
//!
//! The scaffold compiles against Carbon 0.13.x + solana-client 1.18.x
//! on a machine that already has Rust / cargo installed. No code edits
//! required.

use super::{EventDescriptor, InstructionDescriptor, ScaffoldContext};

pub fn render_carbon_scaffold(ctx: &ScaffoldContext<'_>) -> Vec<(String, String)> {
    vec![
        ("Cargo.toml".into(), render_cargo_toml(ctx)),
        ("src/main.rs".into(), render_main_rs(ctx)),
        ("src/events.rs".into(), render_events_rs(ctx)),
        ("src/instructions.rs".into(), render_instructions_rs(ctx)),
        ("idl/program.json".into(), pretty_idl(ctx)),
        ("README.md".into(), render_readme(ctx)),
        (".gitignore".into(), render_gitignore()),
    ]
}

fn render_cargo_toml(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"[package]
name = "{slug}"
version = "0.1.0"
edition = "2021"
description = "Carbon indexer scaffold for {program_name}"

[[bin]]
name = "{bin_name}"
path = "src/main.rs"

[dependencies]
anyhow = "1"
base64 = "0.22"
bs58 = "0.5"
carbon-core = "0.13"
carbon-rpc-transaction-crawler-datasource = "0.13"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tokio = {{ version = "1", features = ["rt-multi-thread", "macros", "signal"] }}
tracing = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter"] }}
"#,
        slug = ctx.project_slug,
        program_name = ctx.program_name,
        bin_name = ctx.project_slug.replace('-', "_"),
    )
}

fn render_main_rs(ctx: &ScaffoldContext<'_>) -> String {
    let event_cases = render_event_cases(&ctx.events);
    let instruction_cases = render_instruction_cases(&ctx.instructions);

    format!(
        r#"//! Generated by Xero's Solana workbench (Phase 7 indexer scaffold).
//!
//! This binary subscribes to signatures for program
//! `{program_id}` via Carbon's RPC crawler datasource and dispatches
//! each tx to the handlers in `instructions.rs` / `events.rs`.
//!
//! Edit `on_event` / `on_instruction` below to add your indexing
//! logic. The top-level shape (datasource → pipeline) is Carbon's
//! canonical pattern — see the Carbon README for more.

use std::sync::Arc;
use std::time::Duration;

use anyhow::Result;
use carbon_core::pipeline::Pipeline;
use carbon_rpc_transaction_crawler_datasource::{{Filters, RpcTransactionCrawler}};
use tracing::{{info, warn}};

mod events;
mod instructions;

const PROGRAM_ID: &str = "{program_id}";
const DEFAULT_RPC_URL: &str = "{rpc_url}";

#[tokio::main]
async fn main() -> Result<()> {{
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::try_from_default_env()
            .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")))
        .init();

    let rpc_url = std::env::var("RPC_URL").unwrap_or_else(|_| DEFAULT_RPC_URL.to_string());
    info!(%rpc_url, program = %PROGRAM_ID, "starting {slug} indexer");

    let program_pubkey: solana_sdk::pubkey::Pubkey = PROGRAM_ID
        .parse()
        .map_err(|err| anyhow::anyhow!("program id is not a valid pubkey: {{err}}"))?;
    let filters = Filters::new(vec![program_pubkey], None);
    let datasource = Arc::new(RpcTransactionCrawler::new(
        rpc_url,
        filters,
        Duration::from_secs(2),
        10,
        None,
        None,
        None,
        None,
        None,
    ));

    let pipeline = Pipeline::builder()
        .datasource(datasource)
        .transaction(|_meta, tx, _slot| {{
            Box::pin(async move {{
                if let Some(meta) = tx.transaction.meta.clone() {{
                    if let Some(logs) = meta.log_messages.clone().into() {{
                        process_logs(&logs);
                    }}
                }}
                Ok(())
            }})
        }})
        .build()?;

    pipeline.run().await?;
    Ok(())
}}

fn process_logs(logs: &[String]) {{
    let mut current_program: Option<String> = None;
    for line in logs {{
        if let Some(rest) = line.strip_prefix("Program ") {{
            if let Some(pid) = rest.split_whitespace().next() {{
                if pid != "log:" && pid != "data:" {{
                    current_program = Some(pid.to_string());
                }}
            }}
        }}
        if let Some(rest) = line.strip_prefix("Program log: ") {{
            if let Some(pid) = current_program.as_deref() {{
                on_instruction_log(pid, rest);
            }}
        }}
        if let Some(rest) = line.strip_prefix("Program data: ") {{
            if let Some(pid) = current_program.as_deref() {{
                on_program_data(pid, rest);
            }}
        }}
    }}
}}

fn on_program_data(program_id: &str, base64_payload: &str) {{
    if program_id != PROGRAM_ID {{
        return;
    }}
    let bytes = match base64::Engine::decode(
        &base64::engine::general_purpose::STANDARD,
        base64_payload,
    ) {{
        Ok(b) => b,
        Err(err) => {{
            warn!(%err, "skipping non-base64 program data");
            return;
        }}
    }};
    if bytes.len() < 8 {{
        return;
    }}
    let mut disc = [0u8; 8];
    disc.copy_from_slice(&bytes[..8]);
    match disc {{
{event_cases}
        _ => info!(?disc, "unknown event discriminator"),
    }}
}}

fn on_instruction_log(program_id: &str, msg: &str) {{
    if program_id != PROGRAM_ID {{
        return;
    }}
    // Anchor prints `Instruction: <Name>` as the first log of each ix.
    if let Some(name) = msg.strip_prefix("Instruction: ") {{
        match name.trim() {{
{instruction_cases}
            other => info!(instruction = other, "unrecognised instruction log"),
        }}
    }}
}}
"#,
        program_id = ctx.program_id,
        rpc_url = ctx.rpc_url,
        slug = ctx.project_slug,
        event_cases = event_cases,
        instruction_cases = instruction_cases,
    )
}

fn render_event_cases(events: &[EventDescriptor]) -> String {
    if events.is_empty() {
        return "        // IDL declares no events — nothing to decode.\n".into();
    }
    let mut out = String::new();
    for event in events {
        let Some(disc) = event.discriminator else {
            continue;
        };
        out.push_str(&format!(
            "        events::{snake}::DISCRIMINATOR => info!(event = \"{name}\", size = bytes.len(), \"decoded event\"),\n",
            snake = event.snake_case,
            name = event.name,
        ));
        let _ = disc; // silences unused warning; disc is encoded in events.rs
    }
    if out.is_empty() {
        out.push_str("        // No events with 8-byte discriminators in this IDL.\n");
    }
    out
}

fn render_instruction_cases(instructions: &[InstructionDescriptor]) -> String {
    if instructions.is_empty() {
        return "            // IDL declares no instructions.\n".into();
    }
    let mut out = String::new();
    for ix in instructions {
        out.push_str(&format!(
            "            \"{pascal}\" => info!(instruction = \"{pascal}\", accounts = {count}, \"ix dispatched\"),\n",
            pascal = ix.pascal_case,
            count = ix.account_count,
        ));
    }
    out
}

fn render_events_rs(ctx: &ScaffoldContext<'_>) -> String {
    let mut out = String::new();
    out.push_str("//! Generated event discriminators from the program IDL.\n");
    out.push_str("//! Regenerate by re-running the Xero scaffold command.\n\n");
    if ctx.events.is_empty() {
        out.push_str("// IDL declares no events.\n");
        return out;
    }
    for event in &ctx.events {
        let Some(disc) = event.discriminator else {
            continue;
        };
        let hex = disc
            .iter()
            .map(|b| format!("0x{b:02x}"))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "pub mod {} {{\n    pub const NAME: &str = \"{}\";\n    pub const DISCRIMINATOR: [u8; 8] = [{hex}];\n}}\n\n",
            event.snake_case, event.name,
        ));
    }
    out
}

fn render_instructions_rs(ctx: &ScaffoldContext<'_>) -> String {
    let mut out = String::new();
    out.push_str("//! Generated instruction constants from the program IDL.\n");
    out.push_str("//! Anchor prints `Instruction: <Name>` as the first log line of\n");
    out.push_str("//! each handler, so these names are what main.rs dispatches on.\n\n");
    if ctx.instructions.is_empty() {
        out.push_str("// IDL declares no instructions.\n");
        return out;
    }
    out.push_str("pub const INSTRUCTION_NAMES: &[(&str, usize)] = &[\n");
    for ix in &ctx.instructions {
        out.push_str(&format!(
            "    (\"{}\", {}),\n",
            ix.pascal_case, ix.account_count
        ));
    }
    out.push_str("];\n");
    out
}

fn render_readme(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"# {project_slug} — Carbon indexer scaffold

Subscribes to program `{program_id}` via Carbon's RPC transaction
crawler and dispatches each decoded tx to the handlers in
`src/main.rs`.

## Run

```sh
RPC_URL={rpc_url} cargo run --release
```

The default RPC URL is baked in for convenience; override via the
`RPC_URL` env var for devnet / mainnet.

## Edit

- Event handling lives in `on_program_data` in `src/main.rs`. The
  match arms call into constants declared in `src/events.rs`.
- Instruction dispatch lives in `on_instruction_log`.
- `idl/program.json` is the IDL the scaffold was generated from. Keep
  it in sync with your program.

## Regenerate

Run the Xero workbench's `solana_indexer_scaffold` command again
with `overwrite=true` to pick up IDL changes.
"#,
        project_slug = ctx.project_slug,
        program_id = ctx.program_id,
        rpc_url = ctx.rpc_url,
    )
}

fn render_gitignore() -> String {
    "target/\nCargo.lock\n".into()
}

fn pretty_idl(ctx: &ScaffoldContext<'_>) -> String {
    serde_json::to_string_pretty(&ctx.idl.value).unwrap_or_else(|_| "{}".into())
}
