//! Standalone TypeScript log-parser scaffold.
//!
//! Produces a minimal Node project (`pnpm install && pnpm start`) that
//! polls `getSignaturesForAddress` + `getTransaction` via
//! `@solana/web3.js`, decodes Anchor event discriminators, and invokes
//! caller-supplied handlers.
//!
//! Deliberately stays small — 1 `package.json`, 1 `tsconfig.json`, 2
//! source files. No framework, no DB wiring, so the developer can
//! glue it into whatever they run in production.

use super::ScaffoldContext;

pub fn render_log_parser_scaffold(ctx: &ScaffoldContext<'_>) -> Vec<(String, String)> {
    vec![
        ("package.json".into(), render_package_json(ctx)),
        ("tsconfig.json".into(), render_tsconfig()),
        ("src/main.ts".into(), render_main_ts(ctx)),
        ("src/handlers.ts".into(), render_handlers_ts(ctx)),
        ("src/idl.ts".into(), render_idl_ts(ctx)),
        ("README.md".into(), render_readme(ctx)),
        (".gitignore".into(), render_gitignore()),
    ]
}

fn render_package_json(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"{{
  "name": "{slug}",
  "version": "0.1.0",
  "private": true,
  "description": "Log-parser indexer scaffold for {program_name}",
  "scripts": {{
    "start": "tsx src/main.ts",
    "build": "tsc",
    "typecheck": "tsc --noEmit"
  }},
  "dependencies": {{
    "@solana/web3.js": "^1.95.0",
    "bs58": "^6.0.0"
  }},
  "devDependencies": {{
    "tsx": "^4.15.0",
    "typescript": "^5.5.0",
    "@types/node": "^20.14.0"
  }}
}}
"#,
        slug = ctx.project_slug,
        program_name = ctx.program_name,
    )
}

fn render_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "outDir": "dist"
  },
  "include": ["src/**/*.ts"]
}
"#
    .into()
}

fn render_main_ts(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"// Generated by Xero's Solana workbench (Phase 7 indexer scaffold).
//
// Polls `getSignaturesForAddress` for the configured program on an
// interval, fetches each new transaction's logs, and dispatches decoded
// events + instruction logs to the handlers in `./handlers.ts`.

import {{ Connection, PublicKey }} from "@solana/web3.js"
import {{ EVENTS, INSTRUCTIONS }} from "./idl"
import {{ onEvent, onInstruction }} from "./handlers"

const PROGRAM_ID = new PublicKey("{program_id}")
const DEFAULT_RPC_URL = "{rpc_url}"
const POLL_INTERVAL_MS = 4_000
const BATCH_LIMIT = 25

async function main(): Promise<void> {{
  const rpcUrl = process.env.RPC_URL ?? DEFAULT_RPC_URL
  const connection = new Connection(rpcUrl, "confirmed")
  console.log(`[{slug}] polling ${{PROGRAM_ID.toBase58()}} on ${{rpcUrl}}`)

  let lastSignature: string | null = null

  while (true) {{
    const signatures = await connection.getSignaturesForAddress(PROGRAM_ID, {{
      limit: BATCH_LIMIT,
      ...(lastSignature ? {{ until: lastSignature }} : {{}}),
    }})
    if (signatures.length === 0) {{
      await sleep(POLL_INTERVAL_MS)
      continue
    }}
    // `getSignaturesForAddress` returns newest-first; we want to
    // process in chronological order so downstream dedup is trivial.
    const ordered = [...signatures].reverse()
    for (const entry of ordered) {{
      const tx = await connection.getTransaction(entry.signature, {{
        commitment: "confirmed",
        maxSupportedTransactionVersion: 0,
      }})
      if (!tx) continue
      const logs = tx.meta?.logMessages ?? []
      await dispatch({{
        signature: entry.signature,
        slot: tx.slot,
        blockTime: tx.blockTime ?? null,
        err: tx.meta?.err ?? null,
        logs,
      }})
    }}
    lastSignature = signatures[0].signature
  }}
}}

interface ParsedTx {{
  signature: string
  slot: number
  blockTime: number | null
  err: unknown
  logs: string[]
}}

async function dispatch(tx: ParsedTx): Promise<void> {{
  let current: string | null = null
  for (const line of tx.logs) {{
    const invokeMatch = line.match(/^Program (\S+) invoke/)
    if (invokeMatch) {{
      current = invokeMatch[1]
      continue
    }}
    if (current !== PROGRAM_ID.toBase58()) continue
    const ixLog = line.match(/^Program log: Instruction: (\w+)/)
    if (ixLog) {{
      const spec = INSTRUCTIONS.find((i) => i.name === ixLog[1])
      await onInstruction({{
        name: ixLog[1],
        accountsExpected: spec?.accountsExpected ?? 0,
        tx,
      }})
      continue
    }}
    const dataLog = line.match(/^Program data: (.+)/)
    if (dataLog) {{
      const bytes = Buffer.from(dataLog[1], "base64")
      if (bytes.length < 8) continue
      const disc = bytes.subarray(0, 8)
      const event = EVENTS.find((e) => Buffer.compare(Buffer.from(e.discriminator), disc) === 0)
      await onEvent({{
        name: event?.name ?? null,
        discriminatorHex: disc.toString("hex"),
        payload: bytes.subarray(8),
        tx,
      }})
    }}
  }}
}}

function sleep(ms: number): Promise<void> {{
  return new Promise((resolve) => setTimeout(resolve, ms))
}}

main().catch((err) => {{
  console.error("[{slug}] fatal:", err)
  process.exitCode = 1
}})
"#,
        program_id = ctx.program_id,
        rpc_url = ctx.rpc_url,
        slug = ctx.project_slug,
    )
}

fn render_handlers_ts(ctx: &ScaffoldContext<'_>) -> String {
    let mut ix_handlers = String::new();
    for ix in &ctx.instructions {
        ix_handlers.push_str(&format!(
            "  // case \"{pascal}\": handle{pascal}(event.tx); break;\n",
            pascal = ix.pascal_case,
        ));
    }
    if ix_handlers.is_empty() {
        ix_handlers.push_str("  // IDL declares no instructions.\n");
    }

    let mut event_handlers = String::new();
    for event in &ctx.events {
        event_handlers.push_str(&format!(
            "  // case \"{pascal}\": handle{pascal}(event.payload, event.tx); break;\n",
            pascal = event.pascal_case,
        ));
    }
    if event_handlers.is_empty() {
        event_handlers.push_str("  // IDL declares no events.\n");
    }

    format!(
        r#"// Handler stubs. Fill these in with whatever indexing logic you need.
// The scaffold dispatches based on the IDL-declared instruction / event names,
// so uncomment the relevant switch arm and implement the handler below.

export interface TxContext {{
  signature: string
  slot: number
  blockTime: number | null
  err: unknown
  logs: string[]
}}

export interface InstructionEvent {{
  name: string
  accountsExpected: number
  tx: TxContext
}}

export interface DecodedEvent {{
  name: string | null
  discriminatorHex: string
  payload: Buffer
  tx: TxContext
}}

export async function onInstruction(event: InstructionEvent): Promise<void> {{
  switch (event.name) {{
{ix_handlers}    default: break;
  }}
}}

export async function onEvent(event: DecodedEvent): Promise<void> {{
  switch (event.name) {{
{event_handlers}    default: break;
  }}
}}
"#,
        ix_handlers = ix_handlers,
        event_handlers = event_handlers,
    )
}

fn render_idl_ts(ctx: &ScaffoldContext<'_>) -> String {
    let events = ctx
        .events
        .iter()
        .filter_map(|e| {
            let disc = e.discriminator?;
            let items = disc
                .iter()
                .map(|b| b.to_string())
                .collect::<Vec<_>>()
                .join(", ");
            Some(format!(
                "  {{ name: \"{}\", discriminator: [{items}] }},",
                e.name
            ))
        })
        .collect::<Vec<_>>()
        .join("\n");
    let instructions = ctx
        .instructions
        .iter()
        .map(|i| {
            format!(
                "  {{ name: \"{pascal}\", accountsExpected: {count} }},",
                pascal = i.pascal_case,
                count = i.account_count,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"// Generated IDL projections. Regenerate via `solana_indexer_scaffold`.

export interface EventSpec {{
  name: string
  discriminator: number[]
}}

export interface InstructionSpec {{
  name: string
  accountsExpected: number
}}

export const EVENTS: EventSpec[] = [
{events}
]

export const INSTRUCTIONS: InstructionSpec[] = [
{instructions}
]
"#,
        events = events,
        instructions = instructions,
    )
}

fn render_readme(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"# {slug} — log-parser indexer

Polls `getSignaturesForAddress` for program `{program_id}` and
dispatches each transaction's decoded logs to the handlers in
`src/handlers.ts`.

## Run

```sh
pnpm install
pnpm start
```

Override the RPC URL via the `RPC_URL` env var. The scaffold defaults
to `{rpc_url}`.

## Edit

- Handler stubs live in `src/handlers.ts`. Uncomment the switch arms
  relevant to your program and implement the `handleXxx` functions.
- IDL projections (event discriminators, instruction names) live in
  `src/idl.ts`. Regenerate the scaffold if the IDL changes.
"#,
        slug = ctx.project_slug,
        program_id = ctx.program_id,
        rpc_url = ctx.rpc_url,
    )
}

fn render_gitignore() -> String {
    "node_modules/\ndist/\n.env\n".into()
}
