//! Helius free-tier webhook handler scaffold.
//!
//! Produces an Express server that Helius can POST enhanced-webhook
//! payloads to. Each arriving transaction is normalised into the same
//! `TxContext` shape the log-parser scaffold uses, then dispatched to
//! per-instruction / per-event handler stubs.

use super::ScaffoldContext;

pub fn render_webhook_scaffold(ctx: &ScaffoldContext<'_>) -> Vec<(String, String)> {
    vec![
        ("package.json".into(), render_package_json(ctx)),
        ("tsconfig.json".into(), render_tsconfig()),
        ("src/server.ts".into(), render_server_ts(ctx)),
        ("src/handlers.ts".into(), render_handlers_ts(ctx)),
        ("src/idl.ts".into(), render_idl_ts(ctx)),
        ("README.md".into(), render_readme(ctx)),
        (".env.example".into(), render_env_example(ctx)),
        (".gitignore".into(), render_gitignore()),
    ]
}

fn render_package_json(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"{{
  "name": "{slug}",
  "version": "0.1.0",
  "private": true,
  "description": "Helius webhook receiver for {program_name}",
  "scripts": {{
    "dev": "tsx src/server.ts",
    "build": "tsc",
    "start": "node dist/server.js",
    "typecheck": "tsc --noEmit"
  }},
  "dependencies": {{
    "express": "^4.19.2"
  }},
  "devDependencies": {{
    "@types/express": "^4.17.21",
    "@types/node": "^20.14.0",
    "tsx": "^4.15.0",
    "typescript": "^5.5.0"
  }}
}}
"#,
        slug = ctx.project_slug,
        program_name = ctx.program_name,
    )
}

fn render_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "outDir": "dist"
  },
  "include": ["src/**/*.ts"]
}
"#
    .into()
}

fn render_server_ts(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"// Generated by Xero's Solana workbench (Phase 7 indexer scaffold).
//
// Lightweight Express server that receives Helius enhanced-webhook
// POSTs, normalises each transaction, and dispatches to handler stubs
// in `./handlers.ts`.

import express, {{ type Request, type Response }} from "express"
import {{ EVENTS, INSTRUCTIONS }} from "./idl"
import {{ onEvent, onInstruction }} from "./handlers"

const PROGRAM_ID = "{program_id}"
const PORT = Number.parseInt(process.env.PORT ?? "8787", 10)
const AUTH_HEADER = process.env.HELIUS_WEBHOOK_AUTH ?? null

const app = express()
app.use(express.json({{ limit: "10mb" }}))

app.post("/webhook", async (req: Request, res: Response) => {{
  if (AUTH_HEADER && req.headers.authorization !== AUTH_HEADER) {{
    res.status(401).json({{ error: "unauthorized" }})
    return
  }}
  const payloads = Array.isArray(req.body) ? req.body : [req.body]
  try {{
    for (const raw of payloads) {{
      await handleTransaction(raw)
    }}
    res.status(200).json({{ ok: true, processed: payloads.length }})
  }} catch (err) {{
    console.error("[{slug}] handler error", err)
    res.status(500).json({{ error: "internal" }})
  }}
}})

app.get("/health", (_req, res) => {{
  res.json({{ ok: true, program: PROGRAM_ID }})
}})

app.listen(PORT, () => {{
  console.log(`[{slug}] webhook listening on :${{PORT}} for ${{PROGRAM_ID}}`)
}})

interface TxContext {{
  signature: string
  slot: number
  blockTime: number | null
  err: unknown
  logs: string[]
}}

async function handleTransaction(raw: unknown): Promise<void> {{
  if (!raw || typeof raw !== "object") return
  const tx = raw as Record<string, unknown>
  const meta = tx.meta as Record<string, unknown> | undefined
  const ctx: TxContext = {{
    signature: String(tx.signature ?? ""),
    slot: Number(tx.slot ?? 0),
    blockTime: typeof tx.blockTime === "number" ? tx.blockTime : null,
    err: meta?.err ?? null,
    logs: Array.isArray(meta?.logMessages) ? (meta!.logMessages as string[]) : [],
  }}
  await dispatch(ctx)
}}

async function dispatch(tx: TxContext): Promise<void> {{
  let current: string | null = null
  for (const line of tx.logs) {{
    const invokeMatch = line.match(/^Program (\S+) invoke/)
    if (invokeMatch) {{
      current = invokeMatch[1]
      continue
    }}
    if (current !== PROGRAM_ID) continue
    const ixLog = line.match(/^Program log: Instruction: (\w+)/)
    if (ixLog) {{
      const spec = INSTRUCTIONS.find((i) => i.name === ixLog[1])
      await onInstruction({{
        name: ixLog[1],
        accountsExpected: spec?.accountsExpected ?? 0,
        tx,
      }})
      continue
    }}
    const dataLog = line.match(/^Program data: (.+)/)
    if (dataLog) {{
      const bytes = Buffer.from(dataLog[1], "base64")
      if (bytes.length < 8) continue
      const disc = bytes.subarray(0, 8)
      const spec = EVENTS.find((e) => Buffer.compare(Buffer.from(e.discriminator), disc) === 0)
      await onEvent({{
        name: spec?.name ?? null,
        discriminatorHex: disc.toString("hex"),
        payload: bytes.subarray(8),
        tx,
      }})
    }}
  }}
}}
"#,
        program_id = ctx.program_id,
        slug = ctx.project_slug,
    )
}

fn render_handlers_ts(ctx: &ScaffoldContext<'_>) -> String {
    let mut ix = String::new();
    for i in &ctx.instructions {
        ix.push_str(&format!(
            "  // case \"{pascal}\": return handle{pascal}(event.tx);\n",
            pascal = i.pascal_case,
        ));
    }
    if ix.is_empty() {
        ix.push_str("  // IDL declares no instructions.\n");
    }

    let mut ev = String::new();
    for e in &ctx.events {
        ev.push_str(&format!(
            "  // case \"{pascal}\": return handle{pascal}(event.payload, event.tx);\n",
            pascal = e.pascal_case,
        ));
    }
    if ev.is_empty() {
        ev.push_str("  // IDL declares no events.\n");
    }

    format!(
        r#"// Handler stubs. Uncomment + implement for each instruction / event
// you care about. The webhook server dispatches here per-transaction.

export interface TxContext {{
  signature: string
  slot: number
  blockTime: number | null
  err: unknown
  logs: string[]
}}

export interface InstructionEvent {{
  name: string
  accountsExpected: number
  tx: TxContext
}}

export interface DecodedEvent {{
  name: string | null
  discriminatorHex: string
  payload: Buffer
  tx: TxContext
}}

export async function onInstruction(event: InstructionEvent): Promise<void> {{
  switch (event.name) {{
{ix}    default: return
  }}
}}

export async function onEvent(event: DecodedEvent): Promise<void> {{
  switch (event.name) {{
{ev}    default: return
  }}
}}
"#,
        ix = ix,
        ev = ev,
    )
}

fn render_idl_ts(ctx: &ScaffoldContext<'_>) -> String {
    let events = ctx
        .events
        .iter()
        .filter_map(|e| {
            let disc = e.discriminator?;
            let bytes = disc
                .iter()
                .map(|b| b.to_string())
                .collect::<Vec<_>>()
                .join(", ");
            Some(format!(
                "  {{ name: \"{}\", discriminator: [{bytes}] }},",
                e.name
            ))
        })
        .collect::<Vec<_>>()
        .join("\n");
    let instructions = ctx
        .instructions
        .iter()
        .map(|i| {
            format!(
                "  {{ name: \"{pascal}\", accountsExpected: {count} }},",
                pascal = i.pascal_case,
                count = i.account_count,
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"// Generated IDL projections. Regenerate via `solana_indexer_scaffold`.

export interface EventSpec {{
  name: string
  discriminator: number[]
}}

export interface InstructionSpec {{
  name: string
  accountsExpected: number
}}

export const EVENTS: EventSpec[] = [
{events}
]

export const INSTRUCTIONS: InstructionSpec[] = [
{instructions}
]
"#,
        events = events,
        instructions = instructions,
    )
}

fn render_env_example(_ctx: &ScaffoldContext<'_>) -> String {
    r#"# Copy to `.env` and fill in.
PORT=8787
# Optional HMAC / shared secret Helius sends back. If set, the server
# rejects any POST whose Authorization header doesn't match.
HELIUS_WEBHOOK_AUTH=
"#
    .into()
}

fn render_readme(ctx: &ScaffoldContext<'_>) -> String {
    format!(
        r#"# {slug} — Helius webhook receiver

Express receiver for [Helius enhanced webhooks](https://www.helius.dev/docs/webhooks).
Normalises each incoming tx and dispatches to handlers in
`src/handlers.ts`.

## Run (local)

```sh
pnpm install
cp .env.example .env
pnpm dev
```

Then point your Helius webhook at `http://<your-host>:$PORT/webhook`
filtered on program `{program_id}`.

## Deploy

The server is a plain Node/Express app — deploy it anywhere a long-
running HTTP process can live (Fly, Railway, Render, a VPS, etc.).

## Edit

Handler stubs live in `src/handlers.ts`. Uncomment the switch arm you
need and implement the `handleXxx` function.
"#,
        slug = ctx.project_slug,
        program_id = ctx.program_id,
    )
}

fn render_gitignore() -> String {
    "node_modules/\ndist/\n.env\n".into()
}
